# Stubs for pandas.io.excel._xlrd (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any
from pandas.io.excel._base import _BaseExcelReader

class _XlrdReader(_BaseExcelReader):
    def __init__(self, filepath_or_buffer: Any) -> None:
        ...

    def load_workbook(self, filepath_or_buffer: Any) -> Any:
        ...

    @property
    def sheet_names(self) -> Any:
        ...

    def get_sheet_by_name(self, name: Any) -> Any:
        ...

    def get_sheet_by_index(self, index: Any) -> Any:
        ...

    def get_sheet_data(self, sheet: Any, convert_float: Any) -> Any:
        ...
