# Stubs for pandas._libs.tslibs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=too-few-public-methods

class IncompatibleFrequency:
    ...


class Period:
    ...
