"""
This type stub file was generated by pyright.
"""

import numba
import numpy as np

"""
Numba 1D mean kernels that can be shared by
* Dataframe / Series
* groupby
* rolling / expanding

Mirrors pandas/_libs/window/aggregation.pyx
"""
@numba.jit(nopython=True, nogil=True, parallel=False)
def add_mean(val: float, nobs: int, sum_x: float, neg_ct: int, compensation: float) -> tuple[int, float, int, float]:
    ...

@numba.jit(nopython=True, nogil=True, parallel=False)
def remove_mean(val: float, nobs: int, sum_x: float, neg_ct: int, compensation: float) -> tuple[int, float, int, float]:
    ...

@numba.jit(nopython=True, nogil=True, parallel=False)
def sliding_mean(values: np.ndarray, start: np.ndarray, end: np.ndarray, min_periods: int) -> np.ndarray:
    ...

