# Stubs for pandas.io.clipboards (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument

from typing import Any, Optional


def read_clipboard(sep: str = ..., **kwargs: Any) -> Any:
    ...


def to_clipboard(obj: Any, excel: bool = ..., sep: Optional[Any] = ...,
                 **kwargs: Any) -> None:
    ...
