# Stubs for pandas.io.spss (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument

from pathlib import Path
from typing import Optional, Sequence, Union
from pandas.core.api import DataFrame


def read_spss(path: Union[str, Path],
              usecols: Optional[Sequence[str]] = ...,
              convert_categoricals: bool = ...) -> DataFrame:
    ...
