# Stubs for pandas.tests.generic.test_label_or_level_utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


def df() -> Any:
    ...


def df_levels(request: Any, df: Any) -> Any:
    ...


def df_ambig(df: Any) -> Any:
    ...


def df_duplabels(df: Any) -> Any:
    ...


def get_labels_levels(df_levels: Any) -> Any:
    ...


def assert_label_reference(frame: Any, labels: Any, axis: Any) -> None:
    ...


def assert_level_reference(frame: Any, levels: Any, axis: Any) -> None:
    ...


def test_is_level_or_label_reference_df_simple(
        df_levels: Any, axis: Any) -> None:
    ...


def test_is_level_reference_df_ambig(df_ambig: Any, axis: Any) -> None:
    ...


def test_is_level_reference_series_simple_axis0(df: Any) -> None:
    ...


def test_is_level_reference_series_axis1_error(df: Any) -> None:
    ...


def test_check_label_or_level_ambiguity_df(df_ambig: Any, axis: Any) -> None:
    ...


def test_check_label_or_level_ambiguity_series(df: Any) -> None:
    ...


def test_check_label_or_level_ambiguity_series_axis1_error(df: Any) -> None:
    ...


def assert_label_values(frame: Any, labels: Any, axis: Any) -> None:
    ...


def assert_level_values(frame: Any, levels: Any, axis: Any) -> None:
    ...


def test_get_label_or_level_values_df_simple(df_levels: Any, axis: Any) -> None:
    ...


def test_get_label_or_level_values_df_ambig(df_ambig: Any, axis: Any) -> None:
    ...


def test_get_label_or_level_values_df_duplabels(
        df_duplabels: Any, axis: Any) -> None:
    ...


def test_get_label_or_level_values_series_axis0(df: Any) -> None:
    ...


def test_get_label_or_level_values_series_axis1_error(df: Any) -> None:
    ...


def assert_labels_dropped(frame: Any, labels: Any, axis: Any) -> None:
    ...


def assert_levels_dropped(frame: Any, levels: Any, axis: Any) -> None:
    ...


def test_drop_labels_or_levels_df(df_levels: Any, axis: Any) -> None:
    ...


def test_drop_labels_or_levels_series(df: Any) -> None:
    ...
