# Stubs for pandas.tests.sparse.frame.test_analytics (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def test_quantile() -> None:
    ...


def test_quantile_multi() -> None:
    ...
