"""
This type stub file was generated by pyright.
"""

from typing import Callable
from pandas._typing import Scalar

def generate_shared_aggregator(func: Callable[..., Scalar], engine_kwargs: dict[str, bool] | None, cache_key_str: str): # -> ((...) -> Unknown) | ((values: ndarray, start: ndarray, end: ndarray, min_periods: int, *args: Unknown) -> ndarray):
    """
    Generate a Numba function that loops over the columns 2D object and applies
    a 1D numba kernel over each column.

    Parameters
    ----------
    func : function
        aggregation function to be applied to each column
    engine_kwargs : dict
        dictionary of arguments to be passed into numba.jit
    cache_key_str: str
        string to access the compiled function of the form
        <caller_type>_<aggregation_type> e.g. rolling_mean, groupby_mean

    Returns
    -------
    Numba function
    """
    ...

