# Stubs for pandas.tests.indexing.multiindex.test_multiindex (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

class TestMultiIndexBasic:
    def test_multiindex_perf_warn(self) -> None:
        ...

    def test_multiindex_contains_dropped(self) -> None:
        ...

    def test_multiindex_is_homogeneous_type(self, data: Any, expected: Any) -> None:
        ...

    def test_indexing_over_hashtable_size_cutoff(self) -> None:
        ...

    def test_multi_nan_indexing(self) -> None:
        ...

    def test_contains(self) -> None:
        ...
