# Stubs for pandas.tests.indexing.multiindex.test_ix (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

class TestMultiIndexIx:
    def test_frame_setitem_ix(self, multiindex_dataframe_random_data: Any) -> None:
        ...

    def test_ix_general(self) -> None:
        ...

    def test_ix_multiindex_missing_label_raises(self) -> None:
        ...

    def test_series_ix_getitem_fancy(self, multiindex_year_month_day_dataframe_random_data: Any) -> None:
        ...
