# Stubs for pandas.tests.indexing.multiindex.test_sorted (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

class TestMultiIndexSorted:
    def test_getitem_multilevel_index_tuple_not_sorted(self) -> None:
        ...

    def test_getitem_slice_not_sorted(self, multiindex_dataframe_random_data: Any) -> None:
        ...

    def test_frame_getitem_not_sorted2(self) -> None:
        ...

    def test_frame_getitem_not_sorted(self, multiindex_dataframe_random_data: Any) -> None:
        ...

    def test_series_getitem_not_sorted(self) -> None:
        ...
