# Stubs for pandas.tests.indexes.multi.test_reshape (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ

from typing import Any

def test_insert(idx: Any) -> None:
    ...


def test_append(idx: Any) -> None:
    ...


def test_repeat() -> None:
    ...


def test_insert_base(idx: Any) -> None:
    ...


def test_delete_base(idx: Any) -> None:
    ...
