# Stubs for pandas.tests.indexes.multi.test_compat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ

from typing import Any


def test_numeric_compat(idx: Any) -> None:
    ...


def test_logical_compat(idx: Any, method: Any) -> None:
    ...


def test_boolean_context_compat(idx: Any) -> None:
    ...


def test_boolean_context_compat2() -> None:
    ...


def test_inplace_mutation_resets_values() -> None:
    ...


def test_ndarray_compat_properties(idx: Any, compat_props: Any) -> None:
    ...


def test_compat(indices: Any) -> None:
    ...


def test_pickle_compat_construction(holder: Any) -> None:
    ...
