# Stubs for pandas.tests.indexes.multi.test_sorting (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ

from typing import Any


def test_sortlevel(idx: Any) -> None:
    ...


def test_sortlevel_not_sort_remaining() -> None:
    ...


def test_sortlevel_deterministic():
    ...


def test_sort(indices: Any) -> None:
    ...


def test_numpy_argsort(idx: Any) -> None:
    ...


def test_unsortedindex() -> None:
    ...


def test_unsortedindex_doc_examples() -> None:
    ...


def test_reconstruct_sort() -> None:
    ...


def test_reconstruct_remove_unused() -> None:
    ...


def test_remove_unused_levels_large(first_type: Any, second_type: Any) -> None:
    ...


def test_remove_unused_nan(level0: Any, level1: Any) -> None:
    ...


def test_argsort(idx: Any) -> None:
    ...
