# Stubs for pandas.tests.indexes.multi.test_partial_indexing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def test_partial_string_timestamp_multiindex() -> None:
    ...
