# Stubs for pandas.tests.indexes.multi.test_indexing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ

from typing import Any

def test_slice_locs_partial(idx: Any) -> None:
    ...


def test_slice_locs() -> None:
    ...


def test_slice_locs_with_type_mismatch() -> None:
    ...


def test_slice_locs_not_sorted() -> None:
    ...


def test_slice_locs_not_contained() -> None:
    ...


def test_putmask_with_wrong_mask(idx: Any) -> None:
    ...


def test_get_indexer() -> None:
    ...


def test_get_indexer_nearest() -> None:
    ...


def test_getitem(idx: Any) -> None:
    ...


def test_getitem_group_select(idx: Any) -> None:
    ...


def test_get_indexer_consistency(idx: Any) -> None:
    ...


def test_getitem_bool_index_all(ind1: Any, ind2: Any) -> None:
    ...


def test_getitem_bool_index_single(ind1: Any, ind2: Any) -> None:
    ...


def test_get_loc(idx: Any) -> None:
    ...


def test_get_loc_duplicates() -> None:
    ...


def test_get_loc_level() -> None:
    ...


def test_get_loc_multiple_dtypes(dtype1: Any, dtype2: Any) -> None:
    ...


def test_get_loc_implicit_cast(level: Any, dtypes: Any) -> None:
    ...


def test_get_loc_cast_bool() -> None:
    ...


def test_get_loc_nan(level: Any, nulls_fixture: Any) -> None:
    ...


def test_get_loc_missing_nan() -> None:
    ...


def test_get_indexer_categorical_time() -> None:
    ...


def test_timestamp_multiindex_indexer() -> None:
    ...
