# Stubs for pandas.tests.indexes.multi.test_copy (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ

from typing import Any


def assert_multiindex_copied(copy: Any, original: Any) -> None:
    ...


def test_copy(idx: Any) -> None:
    ...


def test_shallow_copy(idx: Any) -> None:
    ...


def test_labels_deprecated(idx: Any) -> None:
    ...


def test_view(idx: Any) -> None:
    ...


def test_copy_and_deepcopy(func: Any) -> None:
    ...


def test_copy_method(deep: Any) -> None:
    ...


def test_copy_method_kwargs(deep: Any, kwarg: Any, value: Any) -> None:
    ...
