# Stubs for pandas.tests.indexes.multi.test_equivalence (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ

from typing import Any


def test_equals(idx: Any) -> None:
    ...


def test_equals_op(idx: Any) -> None:
    ...


def test_equals_multi(idx: Any) -> None:
    ...


def test_identical(idx: Any) -> None:
    ...


def test_equals_operator(idx: Any) -> None:
    ...


def test_equals_missing_values() -> None:
    ...


def test_is_() -> None:
    ...


def test_is_all_dates(idx: Any) -> None:
    ...


def test_is_numeric(idx: Any) -> None:
    ...


def test_multiindex_compare() -> None:
    ...
