# Stubs for pandas.core.internals.arrays (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def extract_array(obj: Any, extract_numpy: bool = ...): ...
