# Stubs for pandas.core.internals.concat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-import,unused-argument,invalid-name,redefined-builtin
# pylint: disable=too-few-public-methods,no-self-use,function-redefined
# pylint: disable=redefined-outer-name,too-many-ancestors,super-init-not-called
# pylint: disable=too-many-arguments

from typing import Any, Optional

def get_mgr_concatenation_plan(mgr: Any, indexers: Any) -> Any:
    ...


class JoinUnit:
    block: Any = ...
    indexers: Any = ...
    shape: Any = ...

    def __init__(self, block: Any, shape: Any, indexers:
                 Optional[Any] = ...) -> None:
        ...

    def needs_filling(self) -> Any:
        ...

    def dtype(self) -> Any:
        ...

    def is_na(self) -> bool:
        ...

    def get_reindexed_values(self, empty_dtype: Any, upcasted_na: Any) -> Any:
        ...


def concatenate_join_units(join_units: Any, concat_axis: Any, copy: Any) -> Any:
    ...


def get_empty_dtype_and_na(join_units: Any) -> Any:
    ...


def is_uniform_join_units(join_units: Any) -> bool:
    ...


def is_uniform_reindex(join_units: Any) -> bool:
    ...


def trim_join_unit(join_unit: Any, length: Any) -> JoinUnit:
    ...


def combine_concat_plans(plans: Any, concat_axis: Any) -> Any:
    ...
