# Stubs for pandas.tests.indexes.conftest (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


indices_list: Any

def indices(request: Any) -> Any:
    ...


def one(request: Any) -> Any:
    ...


zeros: Any


def zero(request: Any) -> Any:
    ...
