# Stubs for pandas.tests.indexes.datetimelike (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any
from .common import Base

class DatetimeLike(Base):
    def test_argmax_axis_invalid(self) -> None:
        ...

    def test_can_hold_identifiers(self) -> None:
        ...

    def test_shift_identity(self) -> None:
        ...

    def test_str(self) -> None:
        ...

    def test_view(self) -> None:
        ...

    def test_map_callable(self) -> None:
        ...

    def test_map_dictlike(self, mapper: Any) -> None:
        ...

    def test_asobject_deprecated(self) -> None:
        ...
