# Stubs for pandas.tests.indexes.test_setops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any

COMPATIBLE_INCONSISTENT_PAIRS: Any


def index_pair(request: Any) -> Any:
    ...


def test_union_same_types(indices: Any) -> None:
    ...


def test_union_different_types(index_pair: Any) -> None:
    ...


def test_compatible_inconsistent_pairs(idx_fact1: Any, idx_fact2: Any) -> None:
    ...


def test_union_dtypes(left: Any, right: Any, expected: Any) -> None:
    ...
