"""
This type stub file was generated by pyright.
"""

import numpy as np
from typing import Optional

"""
masked_reductions.py is for reduction algorithms using a mask-based approach
for missing values.
"""
def sum(values: np.ndarray, mask: np.ndarray, *, skipna: bool = ..., min_count: int = ..., axis: Optional[int] = ...): # -> NAType:
    ...

def prod(values: np.ndarray, mask: np.ndarray, *, skipna: bool = ..., min_count: int = ..., axis: Optional[int] = ...): # -> NAType:
    ...

def min(values: np.ndarray, mask: np.ndarray, *, skipna: bool = ..., axis: Optional[int] = ...): # -> NAType:
    ...

def max(values: np.ndarray, mask: np.ndarray, *, skipna: bool = ..., axis: Optional[int] = ...): # -> NAType:
    ...

def mean(values: np.ndarray, mask: np.ndarray, skipna: bool = ...): # -> NAType:
    ...

