# Stubs for pandas.core.dtypes.base (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias

from typing import Any, Dict, List, Optional, Type

_extension_array_shared_docs = dict()  # type: Dict[str, str]


class ExtensionDtype:
    def __eq__(self, other: Any) -> bool:
        ...

    def __hash__(self) -> int:
        ...

    def __ne__(self, other: Any) -> bool:
        ...

    @property
    def na_value(self) -> Any:
        ...

    @property
    def type(self) -> Type:
        ...

    @property
    def kind(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def names(self) -> Optional[List[str]]:
        ...

    @classmethod
    def construct_array_type(cls) -> None:
        ...

    @classmethod
    def construct_from_string(cls: Any, string: str) -> Any:
        ...

    @classmethod
    def is_dtype(cls: Any, dtype: Any) -> bool:
        ...
