# Stubs for pandas.tests.scalar.interval.test_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

def start_shift(request: Any) -> Any:
    ...


class TestOverlaps:
    def test_overlaps_self(self, start_shift: Any, closed: Any) -> None:
        ...

    def test_overlaps_nested(self, start_shift: Any, closed: Any, other_closed: Any) -> None:
        ...

    def test_overlaps_disjoint(self, start_shift: Any, closed: Any, other_closed: Any) -> None:
        ...

    def test_overlaps_endpoint(self, start_shift: Any, closed: Any, other_closed: Any) -> None:
        ...

    def test_overlaps_invalid_type(self, other: Any) -> None:
        ...
