# Stubs for pandas.compat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

PY36: Any
PY37: Any
PYPY: Any

def set_function_name(f: Any, name: Any, cls: Any) -> Any:
    ...


def raise_with_traceback(exc: Any, traceback: Any = ...) -> None:
    ...


def is_platform_little_endian():
    ...


def is_platform_windows():
    ...


def is_platform_linux():
    ...


def is_platform_mac():
    ...


def is_platform_32bit():
    ...
