# Stubs for pandas.compat.pickle_compat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,too-few-public-methods,no-self-use
# pylint: disable=invalid-name,protected-access


import pickle as pkl
from typing import Any, Optional


def load_reduce(self: Any) -> None:
    ...


class Unpickler(pkl._Unpickler):
    def find_class(self, module: Any, name: Any) -> Any:
        ...

def load_newobj(self: Any) -> None:
    ...


def load_newobj_ex(self: Any) -> None:
    ...


def load(fh: Any, encoding: Optional[Any] = ...,
         is_verbose: bool = ...) -> Any:
    ...
