# Stubs for pandas.tests.io.excel.test_xlrd (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
# pylint: disable=blacklisted-name,c-extension-no-member,too-many-ancestors

from typing import Any

xlrd: Any
xlwt: Any

def skip_ods_files(read_ext: Any) -> None:
    ...


def test_read_xlrd_book(read_ext: Any, frame: Any) -> None:
    ...


def test_excel_table_sheet_by_index(datapath: Any, read_ext: Any) -> None:
    ...
