# Stubs for pandas.tests.io.excel.test_openpyxl (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
# pylint: disable=blacklisted-name,c-extension-no-member,too-many-ancestors

from typing import Any

openpyxl: Any
pytestmark: Any

def test_to_excel_styleconverter(ext: Any) -> None:
    ...


def test_write_cells_merge_styled(ext: Any) -> None:
    ...


def test_write_append_mode(ext: Any, mode: Any, expected: Any) -> None:
    ...
