# Stubs for pandas.core.index (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
from pandas.core.indexes.api import (
    CategoricalIndex as CategoricalIndex,
    DatetimeIndex as DatetimeIndex,
    Float64Index as Float64Index,
    Index as Index,
    Int64Index as Int64Index,
    IntervalIndex as IntervalIndex,
    InvalidIndexError as InvalidIndexError,
    MultiIndex as MultiIndex,
    NaT as NaT,
    NumericIndex as NumericIndex,
    PeriodIndex as PeriodIndex,
    RangeIndex as RangeIndex,
    TimedeltaIndex as TimedeltaIndex,
    UInt64Index as UInt64Index,
    _all_indexes_same as _all_indexes_same,
    _get_combined_index as _get_combined_index,
    _get_consensus_names as _get_consensus_names,
    _get_objs_combined_axis as _get_objs_combined_axis,
    _new_Index as _new_Index,
    _union_indexes as _union_indexes,
    ensure_index as ensure_index,
    ensure_index_from_sequences as ensure_index_from_sequences,
)
from pandas.core.indexes.multi import _sparsify as _sparsify
