# Stubs for pandas.core.missing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-import,unused-argument,invalid-name,redefined-builtin
# pylint: disable=too-few-public-methods,no-self-use,function-redefined
# pylint: disable=redefined-outer-name,too-many-ancestors,super-init-not-called

from typing import Any, Optional

def mask_missing(arr: Any, values_to_mask: Any) -> Any:
    ...


def clean_fill_method(method: Any, allow_nearest: bool = ...) -> Any:
    ...


def clean_interp_method(method: Any, **kwargs: Any) -> Any:
    ...


def interpolate_1d(
        xvalues: Any,
        yvalues: Any,
        method: str = "linear",
        limit: Optional[Any] = None,
        limit_direction: str = "forward",
        limit_area: Optional[Any] = None,
        fill_value: Optional[Any] = None,
        bounds_error: bool = False,
        order: Optional[Any] = None,
        **kwargs: Any) -> Any:
    ...


def interpolate_2d(
        values: Any,
        method: str = "pad",
        axis: int = 0,
        limit: Optional[Any] = None,
        fill_value: Optional[Any] = None,
        dtype: Optional[Any] = None) -> Any:
    ...


def pad_1d(
        values: Any,
        limit: Optional[Any] = None,
        mask: Optional[Any] = None,
        dtype: Optional[Any] = None) -> Any:
    ...


def backfill_1d(
        values: Any,
        limit: Optional[Any] = None,
        mask: Optional[Any] = None,
        dtype: Optional[Any] = None) -> Any:
    ...


def pad_2d(
        values: Any,
        limit: Optional[Any] = None,
        mask: Optional[Any] = None,
        dtype: Optional[Any] = None) -> Any:
    ...


def backfill_2d(
        values: Any,
        limit: Optional[Any] = None,
        mask: Optional[Any] = None,
        dtype: Optional[Any] = None) -> Any:
    ...


def get_fill_func(method: Any) -> Any:
    ...


def clean_reindex_fill_method(method: Any) -> Any:
    ...
