# Stubs for pandas.tests.indexing.test_ix (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
# pylint: disable=blacklisted-name,c-extension-no-member,too-many-ancestors

from typing import Any

def test_ix_deprecation() -> None:
    ...


class TestIX:
    def test_ix_loc_setitem_consistency(self) -> None:
        ...

    def test_ix_loc_consistency(self) -> None:
        ...

    def test_ix_weird_slicing(self) -> None:
        ...

    def test_ix_assign_column_mixed(self, float_frame: Any) -> None:
        ...

    def test_ix_get_set_consistency(self) -> None:
        ...

    def test_ix_slicing_strings(self) -> None:
        ...

    def test_ix_setitem_out_of_bounds_axis_0(self) -> None:
        ...

    def test_ix_setitem_out_of_bounds_axis_1(self) -> None:
        ...

    def test_ix_empty_list_indexer_is_ok(self) -> None:
        ...

    def test_ix_duplicate_returns_series(self) -> None:
        ...
