# Stubs for pandas.tests.indexes.timedeltas.test_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ

from typing import Any
from pandas.tests.test_base import Ops


class TestTimedeltaIndexOps(Ops):
    is_valid_objs: Any = ...
    not_valid_objs: Any = ...

    def setup_method(self, method: Any) -> Any:
        ...

    def test_ops_properties(self):
        ...

    def test_value_counts_unique(self) -> None:
        ...

    def test_nonunique_contains(self) -> None:
        ...

    def test_unknown_attribute(self) -> None:
        ...

    def test_order(self) -> None:
        ...

    def test_drop_duplicates_metadata(self) -> None:
        ...

    def test_drop_duplicates(self) -> None:
        ...

    def test_infer_freq(self, freq: Any) -> None:
        ...

    def test_shift(self) -> None:
        ...

    def test_repeat(self) -> None:
        ...

    def test_nat(self) -> None:
        ...

    def test_equals(self) -> None:
        ...

    def test_freq_setter(self, values: Any, freq: Any) -> None:
        ...

    def test_freq_setter_errors(self) -> None:
        ...
