# Stubs for pandas.tests.indexes.timedeltas.test_tools (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ


class TestTimedeltas:
    def test_to_timedelta(self):
        ...

    def test_to_timedelta_invalid(self) -> None:
        ...

    def test_to_timedelta_via_apply(self) -> None:
        ...

    def test_to_timedelta_on_missing_values(self) -> None:
        ...

    def test_to_timedelta_float(self) -> None:
        ...

    def test_to_timedelta_box_deprecated(self) -> None:
        ...
