# Stubs for pandas.tests.indexes.timedeltas.test_timedelta_range (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ

from typing import Any


class TestTimedeltas:
    def test_timedelta_range(self) -> None:
        ...

    def test_linspace_behavior(self, periods: Any, freq: Any) -> None:
        ...

    def test_errors(self) -> None:
        ...
