# Stubs for pandas.tests.arithmetic.conftest (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any

def id_func(x: Any) -> Any:
    ...


def one(request: Any) -> Any:
    ...


zeros: Any


def zero(request: Any) -> Any:
    ...


def numeric_idx(request: Any) -> Any:
    ...


def scalar_td(request: Any) -> Any:
    ...


def three_days(request: Any) -> Any:
    ...


def two_hours(request: Any) -> Any:
    ...


def not_hourly(request: Any) -> Any:
    ...


def not_daily(request: Any) -> Any:
    ...


def mismatched_freq(request: Any) -> Any:
    ...


def box(request: Any) -> Any:
    ...


def box_df_fail(request: Any) -> Any:
    ...


def box_transpose_fail(request: Any) -> Any:
    ...


def box_with_array(request: Any) -> Any:
    ...


box_with_array2 = box_with_array
