# Stubs for pandas.tests.extension.test_period (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
# pylint: disable=blacklisted-name,c-extension-no-member,too-many-ancestors

from typing import Any
from pandas.tests.extension import base

def dtype():
    ...


def data(dtype: Any) -> Any:
    ...


def data_for_twos(dtype: Any) -> Any:
    ...


def data_for_sorting(dtype: Any) -> Any:
    ...


def data_missing(dtype: Any) -> Any:
    ...


def data_missing_for_sorting(dtype: Any) -> Any:
    ...


def data_for_grouping(dtype: Any) -> Any:
    ...


def na_value():
    ...


class BasePeriodTests:
    ...


class TestPeriodDtype(BasePeriodTests, base.BaseDtypeTests):
    ...


class TestConstructors(BasePeriodTests, base.BaseConstructorsTests):
    ...


class TestGetitem(BasePeriodTests, base.BaseGetitemTests):
    ...


class TestMethods(BasePeriodTests, base.BaseMethodsTests):
    def test_combine_add(self, data_repeated: Any) -> None:
        ...


class TestInterface(BasePeriodTests, base.BaseInterfaceTests):
    ...


class TestArithmeticOps(BasePeriodTests, base.BaseArithmeticOpsTests):
    implements: Any = ...
    def test_arith_series_with_scalar(self, data: Any, all_arithmetic_operators: Any) -> None:
        ...

    def test_arith_series_with_array(self, data: Any, all_arithmetic_operators: Any) -> None:
        ...

    def test_add_series_with_extension_array(self, data: Any) -> None:
        ...

    def test_error(self) -> None:  # type: ignore
        ...

    def test_direct_arith_with_series_returns_not_implemented(self, data: Any) -> None:
        ...



class TestCasting(BasePeriodTests, base.BaseCastingTests):
    ...


class TestComparisonOps(BasePeriodTests, base.BaseComparisonOpsTests):
    ...


class TestMissing(BasePeriodTests, base.BaseMissingTests):
    ...


class TestReshaping(BasePeriodTests, base.BaseReshapingTests):
    ...


class TestSetitem(BasePeriodTests, base.BaseSetitemTests):
    ...


class TestGroupby(BasePeriodTests, base.BaseGroupbyTests):
    ...


class TestPrinting(BasePeriodTests, base.BasePrintingTests):
    ...



class TestParsing(BasePeriodTests, base.BaseParsingTests):
    def test_EA_types(self, engine: Any, data: Any) -> None:
        ...
