# Stubs for pandas.tests.extension.base (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=import-error,unused-import,useless-import-alias

from .casting import (
    BaseCastingTests as BaseCastingTests,
)
from .constructors import (
    BaseConstructorsTests as BaseConstructorsTests,
)
from .dtype import (
    BaseDtypeTests as BaseDtypeTests,
)
from .getitem import (
    BaseGetitemTests as BaseGetitemTests,
)
from .groupby import (
    BaseGroupbyTests as BaseGroupbyTests,
)
from .interface import (
    BaseInterfaceTests as BaseInterfaceTests,
)
from .io import (
    BaseParsingTests as BaseParsingTests,
)
from .methods import (
    BaseMethodsTests as BaseMethodsTests,
)
from .missing import (
    BaseMissingTests as BaseMissingTests,
)
from .ops import (
    BaseArithmeticOpsTests as BaseArithmeticOpsTests,
    BaseComparisonOpsTests as BaseComparisonOpsTests,
    BaseOpsUtil as BaseOpsUtil,
)
from .printing import (
    BasePrintingTests as BasePrintingTests,
)
from .reduce import (
    BaseBooleanReduceTests as BaseBooleanReduceTests,
    BaseNoReduceTests as BaseNoReduceTests,
    BaseNumericReduceTests as BaseNumericReduceTests,
)
from .reshaping import (
    BaseReshapingTests as BaseReshapingTests,
)
from .setitem import (
    BaseSetitemTests as BaseSetitemTests,
)
