# Stubs for pandas.tests.extension.base.constructors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
# pylint: disable=blacklisted-name,c-extension-no-member,import-error

from typing import Any
from .base import BaseExtensionTests

class BaseConstructorsTests(BaseExtensionTests):
    def test_from_sequence_from_cls(self, data: Any) -> None:
        ...

    def test_array_from_scalars(self, data: Any) -> None:
        ...

    def test_series_constructor(self, data: Any) -> None:
        ...

    def test_dataframe_constructor_from_dict(self, data: Any, from_series: Any) -> None:
        ...

    def test_dataframe_from_series(self, data: Any) -> None:
        ...

    def test_series_given_mismatched_index_raises(self, data: Any) -> None:
        ...

    def test_from_dtype(self, data: Any) -> None:
        ...

    def test_pandas_array(self, data: Any) -> None:
        ...

    def test_pandas_array_dtype(self, data: Any) -> None:
        ...
