# Stubs for pandas.tests.dtypes.cast.test_upcast (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument
from typing import Any

def test_upcast_error(result: Any) -> None:
    ...


def test_upcast(arr: Any, other: Any, exp_changed: Any, expected: Any) -> None:
    ...


def test_upcast_datetime(
        arr: Any, other: Any, exp_changed: Any, expected: Any) -> None:
    ...
