# Stubs for pandas.tests.dtypes.cast.test_infer_datetimelike (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,invalid-name,no-self-use

from typing import Any


def test_maybe_infer_to_datetimelike_df_construct(
        data: Any, exp_size: Any) -> None:
    ...


def test_maybe_infer_to_datetimelike_ser_construct() -> None:
    ...
