# Stubs for pandas.tests.dtypes.cast.test_construct_object_arr (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument

from typing import Any

def test_cast_1d_array(datum1: Any, datum2: Any) -> None:
    ...


def test_cast_1d_array_invalid_scalar(val: Any) -> None:
    ...
