# Stubs for pandas.tests.dtypes.cast.test_downcast (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,invalid-name

from typing import Any

def test_downcast(arr: Any, expected: Any, dtype: Any) -> None:
    ...


def test_downcast_booleans() -> None:
    ...


def test_downcast_conversion_no_nan(any_real_dtype: Any) -> None:
    ...


def test_downcast_conversion_nan(float_dtype: Any) -> None:
    ...


def test_downcast_conversion_empty(any_real_dtype: Any) -> None:
    ...


def test_datetime_likes_nan(klass: Any) -> None:
    ...


def test_datetime_with_timezone(as_asi: Any) -> None:
    ...
