# Stubs for pandas.tests.dtypes.cast.test_convert_objects (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument

from typing import Any


def test_maybe_convert_objects_copy(data: Any, copy: Any) -> None:
    ...
