# Stubs for pandas.util._validators (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member

from typing import Any

def validate_args(fname: Any, args: Any, max_fname_arg_count: Any, compat_args: Any) -> None:
    ...


def validate_kwargs(fname: Any, kwargs: Any, compat_args: Any) -> None:
    ...


def validate_args_and_kwargs(fname: Any, args: Any, kwargs: Any, max_fname_arg_count: Any, compat_args: Any) -> None:
    ...


def validate_bool_kwarg(value: Any, arg_name: Any) -> None:
    ...


def validate_axis_style_args(data: Any, args: Any, kwargs: Any, arg_name: Any, method_name: Any) -> None:
    ...


def validate_fillna_kwargs(value: Any, method: Any, validate_scalar_dict_value: bool = ...) -> None:
    ...
