# Stubs for pandas.tests.groupby.test_rank (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any

def test_rank_apply() -> None:
    ...


def test_rank_args(
        grps: Any, vals: Any, ties_method: Any, ascending: Any, pct: Any,
        exp: Any) -> None:
    ...


def test_infs_n_nans(
        grps: Any, vals: Any, ties_method: Any, ascending: Any, na_option: Any,
        exp: Any) -> None:
    ...


def test_rank_args_missing(
        grps: Any, vals: Any, ties_method: Any, ascending: Any, na_option: Any,
        pct: Any, exp: Any) -> None:
    ...


def test_rank_resets_each_group(pct: Any, exp: Any) -> None:
    ...


def test_rank_avg_even_vals() -> None:
    ...


def test_rank_object_raises(
        ties_method: Any, ascending: Any, na_option: Any, pct: Any,
        vals: Any) -> None:
    ...


def test_rank_naoption_raises(
        ties_method: Any, ascending: Any, na_option: Any, pct: Any,
        vals: Any) -> None:
    ...


def test_rank_empty_group() -> None:
    ...


def test_rank_zero_div(
        input_key: Any, input_value: Any, output_value: Any) -> None:
    ...
