# Stubs for pandas.tests.arrays.categorical.test_warnings (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


class TestCategoricalWarnings:
    def test_tab_complete_warning(self, ip: Any) -> None:
        ...

    def test_CategoricalAccessor_categorical_deprecation(self) -> None:
        ...

    def test_CategoricalAccessor_name_deprecation(self) -> None:
        ...

    def test_CategoricalAccessor_index_deprecation(self) -> None:
        ...
