# Stubs for pandas.tests.arrays.categorical.test_algos (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


def test_factorize(categories: Any, ordered: Any) -> None:
    ...


def test_factorized_sort() -> None:
    ...


def test_factorized_sort_ordered() -> None:
    ...


def test_isin_cats() -> None:
    ...


def test_isin_empty(empty: Any) -> None:
    ...


class TestTake:
    def test_take_warns(self) -> None:
        ...

    def test_take_positive_no_warning(self) -> None:
        ...

    def test_take_bounds(self, allow_fill: Any) -> None:
        ...

    def test_take_empty(self, allow_fill: Any) -> None:
        ...

    def test_positional_take(self, ordered_fixture: Any) -> None:
        ...

    def test_positional_take_unobserved(self, ordered_fixture: Any) -> None:
        ...

    def test_take_allow_fill(self) -> None:
        ...

    def test_take_fill_with_negative_one(self) -> None:
        ...

    def test_take_fill_value(self) -> None:
        ...

    def test_take_fill_value_new_raises(self) -> None:
        ...
