# Stubs for pandas.tests.arrays.categorical.test_missing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


class TestCategoricalMissing:
    def test_na_flags_int_categories(self) -> None:
        ...

    def test_nan_handling(self) -> None:
        ...

    def test_set_dtype_nans(self) -> None:
        ...

    def test_set_item_nan(self) -> None:
        ...

    def test_fillna_raises(self, fillna_kwargs: Any, msg: Any) -> None:
        ...

    def test_fillna_iterable_category(self, named: Any) -> None:
        ...
