# Stubs for pandas.tests.arrays.categorical.test_repr (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from pandas.tests.arrays.categorical.common import TestCategorical


class TestCategoricalReprWithFactor(TestCategorical):
    def test_print(self) -> None:
        ...


class TestCategoricalRepr:
    def test_big_print(self) -> None:
        ...

    def test_empty_print(self) -> None:
        ...

    def test_print_none_width(self) -> None:
        ...

    def test_unicode_print(self) -> None:
        ...

    def test_categorical_repr(self) -> None:
        ...

    def test_categorical_repr_ordered(self) -> None:
        ...

    def test_categorical_repr_datetime(self) -> None:
        ...

    def test_categorical_repr_datetime_ordered(self) -> None:
        ...

    def test_categorical_repr_int_with_nan(self) -> None:
        ...

    def test_categorical_repr_period(self) -> None:
        ...

    def test_categorical_repr_period_ordered(self) -> None:
        ...

    def test_categorical_repr_timedelta(self) -> None:
        ...

    def test_categorical_repr_timedelta_ordered(self) -> None:
        ...

    def test_categorical_index_repr(self) -> None:
        ...

    def test_categorical_index_repr_ordered(self) -> None:
        ...

    def test_categorical_index_repr_datetime(self) -> None:
        ...

    def test_categorical_index_repr_datetime_ordered(self) -> None:
        ...

    def test_categorical_index_repr_period(self) -> None:
        ...

    def test_categorical_index_repr_period_ordered(self) -> None:
        ...

    def test_categorical_index_repr_timedelta(self) -> None:
        ...

    def test_categorical_index_repr_timedelta_ordered(self) -> None:
        ...
