# Stubs for pandas.tests.arrays.categorical.test_analytics (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


class TestCategoricalAnalytics:
    def test_min_max(self) -> None:
        ...

    def test_mode(self, values: Any, categories: Any, exp_mode: Any) -> None:
        ...

    def test_searchsorted(self) -> None:
        ...

    def test_unique(self) -> None:
        ...

    def test_unique_ordered(self) -> None:
        ...

    def test_unique_index_series(self) -> None:
        ...

    def test_shift(self) -> None:
        ...

    def test_nbytes(self) -> None:
        ...

    def test_memory_usage(self) -> None:
        ...

    def test_map(self):
        ...

    def test_validate_inplace(self) -> None:
        ...

    def test_isna(self) -> None:
        ...
