# Stubs for pandas.tests.io.conftest (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

def tips_file(datapath: Any) -> Any:
    ...


def jsonl_file(datapath: Any) -> Any:
    ...


def salaries_table(datapath: Any) -> Any:
    ...


def s3_resource(tips_file: Any, jsonl_file: Any) -> None:
    ...
