# Stubs for pandas.tests.io.test_common (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

class CustomFSPath:
    path: Any = ...
    def __init__(self, path: Any) -> None:
        ...

    def __fspath__(self) -> Any:
        ...


path_types: Any
HERE: Any

class TestCommonIOCapabilities:
    data1: str = ...
    def test_expand_user(self) -> None:
        ...

    def test_expand_user_normal_path(self) -> None:
        ...

    def test_stringify_path_pathlib(self) -> None:
        ...

    def test_stringify_path_localpath(self) -> None:
        ...

    def test_stringify_path_fspath(self) -> None:
        ...

    def test_infer_compression_from_path(self, extension: Any, expected: Any, path_type: Any) -> None:
        ...

    def test_get_filepath_or_buffer_with_path(self) -> None:
        ...

    def test_get_filepath_or_buffer_with_buffer(self) -> None:
        ...

    def test_iterator(self) -> None:
        ...

    def test_read_non_existant(self, reader: Any, module: Any, error_class: Any, fn_ext: Any) -> None:
        ...

    def test_read_expands_user_home_dir(self, reader: Any, module: Any, error_class: Any, fn_ext: Any, monkeypatch: Any) -> None:
        ...

    def test_read_fspath_all(self, reader: Any, module: Any, path: Any, datapath: Any) -> None:
        ...

    def test_write_fspath_all(self, writer_name: Any, writer_kwargs: Any, module: Any) -> None:
        ...

    def test_write_fspath_hdf5(self) -> None:
        ...


def mmap_file(datapath: Any) -> Any:
    ...


class TestMMapWrapper:
    def test_constructor_bad_file(self, mmap_file: Any) -> None:
        ...

    def test_get_attr(self, mmap_file: Any) -> None:
        ...

    def test_next(self, mmap_file: Any) -> None:
        ...

    def test_unknown_engine(self) -> None:
        ...
