# Stubs for pandas.tseries.api (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-import,useless-import-alias


from pandas.tseries.frequencies import infer_freq as infer_freq
import pandas.tseries.offsets as offsets
