# Stubs for pandas.tests.scalar.period.test_asfreq (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

class TestFreqConversion:
    def test_asfreq_near_zero(self, freq: Any) -> None:
        ...

    def test_asfreq_near_zero_weekly(self) -> None:
        ...

    def test_to_timestamp_out_of_bounds(self) -> None:
        ...

    def test_asfreq_corner(self) -> None:
        ...

    def test_conv_annual(self) -> None:
        ...

    def test_conv_quarterly(self) -> None:
        ...

    def test_conv_monthly(self) -> None:
        ...

    def test_conv_weekly(self) -> None:
        ...

    def test_conv_weekly_legacy(self) -> None:
        ...

    def test_conv_business(self) -> None:
        ...

    def test_conv_daily(self) -> None:
        ...

    def test_conv_hourly(self) -> None:
        ...

    def test_conv_minutely(self) -> None:
        ...

    def test_conv_secondly(self) -> None:
        ...

    def test_asfreq_mult(self) -> None:
        ...

    def test_asfreq_combined(self) -> None:
        ...

    def test_asfreq_MS(self) -> None:
        ...
