# Stubs for pandas.tests.plotting.test_backend (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

def test_matplotlib_backend_error() -> None:
    ...


def test_backend_is_not_module() -> None:
    ...


def test_backend_is_correct(monkeypatch: Any) -> None:
    ...
