# Stubs for pandas.tests.plotting.test_groupby (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from pandas.tests.plotting.common import TestPlotBase

class TestDataFrameGroupByPlots(TestPlotBase):
    def test_series_groupby_plotting_nominally_works(self) -> None:
        ...

    def test_plotting_with_float_index_works(self):
        ...

    def test_hist_single_row(self) -> None:
        ...

    def test_plot_submethod_works(self) -> None:
        ...

    def test_plot_kwargs(self) -> None:
        ...
