# Stubs for pandas.tests.util.conftest (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any

def check_dtype(request: Any) -> None:
    ...


def check_exact(request: Any) -> None:
    ...


def check_index_type(request: Any) -> None:
    ...


def check_less_precise(request: Any) -> None:
    ...


def check_categorical(request: Any) -> None:
    ...
