# Stubs for pandas.tests.util.test_assert_categorical_equal (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


def test_categorical_equal(c: Any) -> None:
    ...


def test_categorical_equal_order_mismatch(check_category_order: Any) -> None:
    ...


def test_categorical_equal_categories_mismatch() -> None:
    ...


def test_categorical_equal_codes_mismatch() -> None:
    ...


def test_categorical_equal_ordered_mismatch() -> None:
    ...


def test_categorical_equal_object_override(obj: Any) -> None:
    ...
