# Stubs for pandas.tests.util.test_assert_frame_equal (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


def by_blocks_fixture(request: Any) -> Any:
    ...


def obj_fixture(request: Any) -> Any:
    ...


def test_frame_equal_row_order_mismatch(
        check_like: Any, obj_fixture: Any) -> None:
    ...


def test_frame_equal_shape_mismatch(
        df1: Any, df2: Any, obj_fixture: Any) -> None:
    ...


def test_frame_equal_index_dtype_mismatch(
        df1: Any, df2: Any, msg: Any, check_index_type: Any) -> None:
    ...


def test_empty_dtypes(check_dtype: Any) -> None:
    ...


def test_frame_equal_index_mismatch(obj_fixture: Any) -> None:
    ...


def test_frame_equal_columns_mismatch(obj_fixture: Any) -> None:
    ...


def test_frame_equal_block_mismatch(
        by_blocks_fixture: Any, obj_fixture: Any) -> None:
    ...


def test_frame_equal_unicode(
        df1: Any, df2: Any, msg: Any, by_blocks_fixture: Any, obj_fixture: Any) -> None:
    ...
