# Stubs for pandas.tests.util.test_validate_args (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,blacklisted-name

from typing import Any


def test_bad_min_fname_arg_count() -> None:
    ...


def test_bad_arg_length_max_value_single() -> None:
    ...


def test_bad_arg_length_max_value_multiple() -> None:
    ...


def test_not_all_defaults(i: Any) -> None:
    ...


def test_validation() -> None:
    ...
