# Stubs for pandas.tests.util.test_assert_extension_array_equal (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


def test_assert_extension_array_equal_not_exact(kwargs: Any) -> None:
    ...


def test_assert_extension_array_equal_less_precise(check_less_precise: Any) -> None:
    ...


def test_assert_extension_array_equal_dtype_mismatch(check_dtype: Any) -> None:
    ...


def test_assert_extension_array_equal_missing_values() -> None:
    ...


def test_assert_extension_array_equal_non_extension_array(side: Any) -> None:
    ...
