# Stubs for pandas.tests.util.test_validate_kwargs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,blacklisted-name

from typing import Any


def test_bad_kwarg() -> None:
    ...


def test_not_all_none(i: Any) -> None:
    ...


def test_validation() -> None:
    ...


def test_validate_bool_kwarg_fail(name: Any, value: Any) -> None:
    ...


def test_validate_bool_kwarg(name: Any, value: Any) -> None:
    ...
