# Stubs for pandas.tests.util.test_deprecate (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def new_func():
    ...


def new_func_no_docstring():
    ...


def new_func_wrong_docstring():
    ...


def new_func_with_deprecation() -> None:
    ...


def test_deprecate_ok() -> None:
    ...


def test_deprecate_no_docstring() -> None:
    ...


def test_deprecate_wrong_docstring() -> None:
    ...
