# Stubs for pandas.tests.util.test_assert_numpy_array_equal (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


def test_assert_numpy_array_equal_shape_mismatch() -> None:
    ...


def test_assert_numpy_array_equal_bad_type() -> None:
    ...


def test_assert_numpy_array_equal_class_mismatch(
        a: Any, b: Any, klass1: Any, klass2: Any) -> None:
    ...


def test_assert_numpy_array_equal_value_mismatch1() -> None:
    ...


def test_assert_numpy_array_equal_value_mismatch2() -> None:
    ...


def test_assert_numpy_array_equal_value_mismatch3() -> None:
    ...


def test_assert_numpy_array_equal_value_mismatch4() -> None:
    ...


def test_assert_numpy_array_equal_value_mismatch5() -> None:
    ...


def test_assert_numpy_array_equal_value_mismatch6() -> None:
    ...


def test_assert_numpy_array_equal_shape_mismatch_override() -> None:
    ...


def test_numpy_array_equal_unicode() -> None:
    ...


def test_numpy_array_equal_object() -> None:
    ...


def test_numpy_array_equal_copy_flag(other_type: Any, check_same: Any) -> None:
    ...
