# Stubs for pandas.tests.util.test_assert_interval_array_equal (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


def test_interval_array_equal(kwargs: Any) -> None:
    ...


def test_interval_array_equal_closed_mismatch() -> None:
    ...


def test_interval_array_equal_periods_mismatch() -> None:
    ...


def test_interval_array_equal_end_mismatch() -> None:
    ...


def test_interval_array_equal_start_mismatch() -> None:
    ...
