# Stubs for pandas.tests.util.test_safe_import (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


def test_safe_import_non_existent(name: Any) -> None:
    ...


def test_safe_import_exists() -> None:
    ...


def test_safe_import_versions(min_version: Any, valid: Any) -> None:
    ...


def test_safe_import_dummy(
        monkeypatch: Any, min_version: Any, valid: Any) -> None:
    ...
