# Stubs for pandas.plotting._matplotlib.timeseries (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member

from typing import Any, Optional

def tsplot(series: Any, plotf: Any, ax: Optional[Any] = ..., **kwargs: Any) -> Any:
    ...

def format_timedelta_ticks(x: Any, pos: Any, n_decimals: Any) -> Any:
    ...

def format_dateaxis(subplot: Any, freq: Any, index: Any) -> None:
    ...
