# Stubs for pandas.plotting._matplotlib.tools (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ

from typing import Any, Optional

def format_date_labels(ax: Any, rot: Any) -> None:
    ...

def table(ax: Any, data: Any, rowLabels: Optional[Any] = ..., colLabels: Optional[Any] = ..., **kwargs: Any) -> Any:
    ...
