# Stubs for pandas.io.sas.sasreader (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
# pylint: disable=blacklisted-name,c-extension-no-member,import-error

from typing import Any, Optional


def read_sas(filepath_or_buffer: Any, format: Optional[Any] = ...,
             index: Optional[Any] = ..., encoding: Optional[Any] = ...,
             chunksize: Optional[Any] = ..., iterator: bool = ...) -> Any:
    ...
