# Stubs for pandas.tests.indexes.datetimes.test_astype (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any

class TestDatetimeIndex:
    def test_astype(self) -> None:
        ...

    def test_astype_uint(self) -> None:
        ...

    def test_astype_with_tz(self) -> None:
        ...

    def test_astype_str_compat(self) -> None:
        ...

    def test_astype_str(self) -> None:
        ...

    def test_astype_datetime64(self) -> None:
        ...

    def test_astype_object(self) -> None:
        ...

    def test_astype_object_tz(self, tz: Any) -> None:
        ...

    def test_astype_object_with_nat(self) -> None:
        ...

    def test_astype_raises(self, dtype: Any) -> None:
        ...

    def test_index_convert_to_datetime_array(self) -> None:
        ...

    def test_index_convert_to_datetime_array_explicit_pytz(self) -> None:
        ...

    def test_index_convert_to_datetime_array_dateutil(self) -> None:
        ...

    def test_integer_index_astype_datetime(self, tz: Any, dtype: Any) -> None:
        ...


class TestToPeriod:
    index: Any = ...

    def setup_method(self, method: Any) -> None:
        ...

    def test_to_period_millisecond(self) -> None:
        ...

    def test_to_period_microsecond(self) -> None:
        ...

    def test_to_period_tz(self, tz: Any) -> None:
        ...

    def test_to_period_tz_utc_offset_consistency(self, tz: Any) -> None:
        ...

    def test_to_period_nofreq(self) -> None:
        ...

    def test_astype_category(self, tz: Any) -> None:
        ...

    def test_astype_array_fallback(self, tz: Any) -> None:
        ...
