# Stubs for pandas.tests.series.common (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method

class TestData:
    def ts(self):
        ...

    def series(self):
        ...

    def objSeries(self):
        ...

    def empty(self):
        ...
