# Stubs for pandas.tests.series.test_combine_concat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method

from typing import Any

class TestSeriesCombine:
    def test_append(self, datetime_series: Any, string_series: Any, object_series: Any) -> None:
        ...

    def test_append_many(self, datetime_series: Any) -> None:
        ...

    def test_append_duplicates(self) -> None:
        ...

    def test_combine_scalar(self):
        ...

    def test_combine_first(self) -> None:
        ...

    def test_update(self) -> None:
        ...

    def test_update_dtypes(self, other: Any, dtype: Any, expected: Any) -> None:
        ...

    def test_concat_empty_series_dtypes_roundtrips(self):
        ...

    def test_combine_first_dt_tz_values(self, tz_naive_fixture: Any) -> None:
        ...

    def test_concat_empty_series_dtypes(self) -> None:
        ...

    def test_combine_first_dt64(self) -> None:
        ...


class TestTimeseries:
    def test_append_concat(self) -> None:
        ...

    def test_append_concat_tz(self) -> None:
        ...

    def test_append_concat_tz_explicit_pytz(self) -> None:
        ...

    def test_append_concat_tz_dateutil(self) -> None:
        ...
