# Stubs for pandas.tests.series.test_rank (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any
from pandas.tests.series.common import TestData


class TestSeriesRank(TestData):
    s: Any = ...
    results: Any = ...
    def test_rank(self) -> None:
        ...

    def test_rank_categorical(self) -> None:
        ...

    def test_rank_signature(self) -> None:
        ...

    def test_rank_inf(self, contents: Any, dtype: Any) -> None:
        ...

    def test_rank_tie_methods(self) -> None:
        ...

    def test_rank_tie_methods_on_infs_nans(self, method: Any, na_option: Any, ascending: Any) -> None:
        ...

    def test_rank_desc_mix_nans_infs(self) -> None:
        ...

    def test_rank_methods_series(self) -> None:
        ...

    def test_rank_dense_method(self) -> None:
        ...

    def test_rank_descending(self) -> None:
        ...

    def test_rank_int(self) -> None:
        ...

    def test_rank_object_bug(self) -> None:
        ...

    def test_rank_modify_inplace(self) -> None:
        ...


def test_rank_dense_pct(dtype: Any, ser: Any, exp: Any) -> None:
    ...

def test_rank_min_pct(dtype: Any, ser: Any, exp: Any) -> None:
    ...

def test_rank_max_pct(dtype: Any, ser: Any, exp: Any) -> None:
    ...

def test_rank_average_pct(dtype: Any, ser: Any, exp: Any) -> None:
    ...

def test_rank_first_pct(dtype: Any, ser: Any, exp: Any) -> None:
    ...

def test_pct_max_many_rows() -> None:
    ...
