# Stubs for pandas.tests.series.test_block_internals (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method

class TestSeriesBlockInternals:
    def test_setitem_invalidates_datetime_index_freq(self) -> None:
        ...

    def test_dt64tz_setitem_does_not_mutate_dti(self) -> None:
        ...
