# Stubs for pandas.tests.series.test_alter_axes (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method

from typing import Any

class TestSeriesAlterAxes:
    def test_setindex(self, string_series: Any) -> None:
        ...

    def test_rename(self, datetime_series: Any) -> None:
        ...

    def test_rename_by_series(self) -> None:
        ...

    def test_rename_set_name(self) -> None:
        ...

    def test_rename_set_name_inplace(self) -> None:
        ...

    def test_rename_axis_supported(self) -> None:
        ...

    def test_set_name_attribute(self) -> None:
        ...

    def test_set_name(self) -> None:
        ...

    def test_rename_inplace(self, datetime_series: Any) -> None:
        ...

    def test_set_index_makes_timeseries(self) -> None:
        ...

    def test_reset_index(self) -> None:
        ...

    def test_reset_index_name(self) -> None:
        ...

    def test_reset_index_level(self) -> None:
        ...

    def test_reset_index_range(self) -> None:
        ...

    def test_reorder_levels(self) -> None:
        ...

    def test_rename_axis_mapper(self) -> None:
        ...

    def test_rename_axis_inplace(self, datetime_series: Any) -> None:
        ...

    def test_rename_axis_none(self, kwargs: Any) -> None:
        ...

    def test_set_axis_inplace_axes(self, axis_series: Any) -> None:
        ...

    def test_set_axis_inplace(self) -> None:
        ...

    def test_set_axis_prior_to_deprecation_signature(self) -> None:
        ...

    def test_reset_index_drop_errors(self) -> None:
        ...

    def test_droplevel(self) -> None:
        ...
