# Stubs for pandas.tests.series.test_asof (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method

class TestSeriesAsof:
    def test_basic(self) -> None:
        ...

    def test_scalar(self) -> None:
        ...

    def test_with_nan(self) -> None:
        ...

    def test_periodindex(self) -> None:
        ...

    def test_errors(self) -> None:
        ...

    def test_all_nans(self) -> None:
        ...
