# Stubs for pandas.tests.io.formats.test_to_latex (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
# pylint: disable=blacklisted-name,c-extension-no-member,too-many-ancestors

from typing import Any

class TestToLatex:
    def test_to_latex_filename(self, float_frame: Any) -> None:
        ...

    def test_to_latex(self, float_frame: Any) -> None:
        ...

    def test_to_latex_format(self, float_frame: Any) -> None:
        ...

    def test_to_latex_empty(self) -> None:
        ...

    def test_to_latex_with_formatters(self):
        ...

    def test_to_latex_multiindex(self) -> None:
        ...

    def test_to_latex_multiindex_dupe_level(self) -> None:
        ...

    def test_to_latex_multicolumnrow(self) -> None:
        ...

    def test_to_latex_escape(self) -> None:
        ...

    def test_to_latex_special_escape(self) -> None:
        ...

    def test_to_latex_longtable(self, float_frame: Any) -> None:
        ...

    def test_to_latex_escape_special_chars(self) -> None:
        ...

    def test_to_latex_no_header(self) -> None:
        ...

    def test_to_latex_specified_header(self) -> None:
        ...

    def test_to_latex_decimal(self, float_frame: Any) -> None:
        ...

    def test_to_latex_series(self) -> None:
        ...

    def test_to_latex_bold_rows(self) -> None:
        ...

    def test_to_latex_no_bold_rows(self) -> None:
        ...

    def test_to_latex_multiindex_names(self, name0: Any, name1: Any, axes: Any) -> None:
        ...

    def test_to_latex_multiindex_nans(self, one_row: Any) -> None:
        ...

    def test_to_latex_non_string_index(self) -> None:
        ...

    def test_to_latex_midrule_location(self) -> None:
        ...

    def test_to_latex_multiindex_empty_name(self) -> None:
        ...

    def test_to_latex_float_format_no_fixed_width(self) -> None:
        ...

    def test_to_latex_multindex_header(self) -> None:
        ...
