# Stubs for pandas.tests.io.formats.test_printing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
# pylint: disable=blacklisted-name,c-extension-no-member,too-many-ancestors

def test_adjoin() -> None:
    ...

def test_repr_binary_type() -> None:
    ...


class TestFormattBase:
    def test_adjoin(self) -> None:
        ...

    def test_adjoin_unicode(self) -> None:
        ...

    def test_justify(self):
        ...

    def test_east_asian_len(self) -> None:
        ...

    def test_ambiguous_width(self) -> None:
        ...


class TestTableSchemaRepr:
    @classmethod
    def setup_class(cls) -> None:
        ...

    def test_publishes(self) -> None:
        ...

    def test_publishes_not_implemented(self) -> None:
        ...

    def test_config_on(self) -> None:
        ...

    def test_config_default_off(self) -> None:
        ...

    def test_enable_data_resource_formatter(self) -> None:
        ...
