# Stubs for pandas.tests.io.formats.test_eng_formatting (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
# pylint: disable=blacklisted-name,c-extension-no-member,too-many-ancestors

from typing import Any

class TestEngFormatter:
    def test_eng_float_formatter(self) -> None:
        ...

    def compare(self, formatter: Any, input: Any, output: Any) -> None:
        ...

    def compare_all(self, formatter: Any, in_out: Any) -> None:
        ...

    def test_exponents_with_eng_prefix(self) -> None:
        ...

    def test_exponents_without_eng_prefix(self) -> None:
        ...

    def test_rounding(self) -> None:
        ...

    def test_nan(self) -> None:
        ...

    def test_inf(self) -> None:
        ...
