# Stubs for pandas.io.clipboard.windows (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument

from typing import Any

class CheckedCall:
    def __init__(self, f: Any) -> None:
        ...

    def __call__(self, *args: Any) -> Any:
        ...

    def __setattr__(self, key: Any, value: Any) -> None:
        ...

def init_windows_clipboard() -> Any:
    ...
