"""
This type stub file was generated by pyright.
"""

"""
Entrypoint for testing from the top-level namespace.
"""
PKG = ...
def test(extra_args=...):
    """
    Run the pandas test suite using pytest.
    """
    ...

__all__ = ["test"]
