# Stubs for pandas.tests.test_join (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
# pylint: disable=blacklisted-name,c-extension-no-member,too-many-ancestors

class TestIndexer:
    def test_outer_join_indexer(self) -> None:
        ...


def test_left_join_indexer_unique() -> None:
    ...


def test_left_outer_join_bug() -> None:
    ...


def test_inner_join_indexer() -> None:
    ...


def test_outer_join_indexer() -> None:
    ...


def test_left_join_indexer() -> None:
    ...


def test_left_join_indexer2() -> None:
    ...


def test_outer_join_indexer2() -> None:
    ...


def test_inner_join_indexer2() -> None:
    ...


def test_merge_join_categorical_multiindex() -> None:
    ...
