# Stubs for pandas.tests.test_downstream (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


def import_module(name: Any) -> Any:
    ...


def df() -> Any:
    ...


def test_dask(df: Any) -> None:
    ...


def test_xarray(df: Any) -> None:
    ...


def test_oo_optimizable() -> None:
    ...


def test_statsmodels() -> None:
    ...


def test_scikit_learn(df: Any) -> None:
    ...


def test_seaborn() -> None:
    ...


def test_pandas_gbq(df: Any) -> None:
    ...


def test_pandas_datareader() -> None:
    ...


def test_geopandas() -> None:
    ...


def test_geopandas_coordinate_indexer():
    ...


def test_pyarrow(df: Any) -> None:
    ...


def test_missing_required_dependency() -> None:
    ...
