# Stubs for pandas.tests.test_optional_dependency (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.


def test_import_optional() -> None:
    ...


def test_xlrd_version_fallback() -> None:
    ...


def test_bad_version() -> None:
    ...


def test_no_version_raises() -> None:
    ...
