# Stubs for pandas.tests.test_errors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any

def test_exception_importable(exc: Any) -> None:
    ...


def test_catch_oob() -> None:
    ...


def test_error_rename() -> None:
    ...


class Foo:
    @classmethod
    def classmethod(cls) -> None:
        ...

    @property
    def property(self) -> None:
        ...

    def method(self) -> None:
        ...


def test_AbstractMethodError_classmethod() -> None:
    ...
