# Stubs for pandas.tests.test_sorting (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
# pylint: disable=blacklisted-name,c-extension-no-member,too-many-ancestors

from typing import Any

class TestSorting:
    def test_int64_overflow(self) -> None:
        ...

    def test_int64_overflow_moar(self) -> None:
        ...

    def test_lexsort_indexer(self) -> None:
        ...

    def test_nargsort(self) -> None:
        ...


class TestMerge:
    def test_int64_overflow_issues(self):
        ...


def test_decons() -> None:
    ...


class TestSafeSort:
    def test_basic_sort(self) -> None:
        ...

    def test_labels(self, verify: Any) -> None:
        ...

    def test_labels_out_of_bound(self, na_sentinel: Any) -> None:
        ...

    def test_mixed_integer(self) -> None:
        ...

    def test_mixed_integer_from_list(self) -> None:
        ...

    def test_unsortable(self) -> None:
        ...

    def test_exceptions(self) -> None:
        ...

    def test_extension_array(self) -> None:
        ...

    def test_extension_array_labels(self, verify: Any, na_sentinel: Any) -> None:
        ...
