from .std import tqdm as std_tqdm
from typing import Any, Optional

class tqdm_asyncio(std_tqdm):
    iterable_awaitable: bool = ...
    iterable_next: Any = ...
    iterable_iterator: Any = ...
    def __init__(self, iterable: Optional[Any] = ..., *args: Any, **kwargs: Any) -> None: ...
    def __aiter__(self): ...
    async def __anext__(self): ...
    def send(self, *args: Any, **kwargs: Any): ...
    @classmethod
    def as_completed(cls, fs: Any, *, loop: Optional[Any] = ..., timeout: Optional[Any] = ..., total: Optional[Any] = ..., **tqdm_kwargs: Any) -> None: ...
    @classmethod
    async def gather(cls, *fs: Any, loop: Optional[Any] = ..., timeout: Optional[Any] = ..., total: Optional[Any] = ..., **tqdm_kwargs: Any): ...

def tarange(*args: Any, **kwargs: Any): ...
tqdm = tqdm_asyncio
trange = tarange
