from dask.callbacks import Callback
from typing import Any, Optional

class TqdmCallback(Callback):
    tqdm_class: Any = ...
    def __init__(self, start: Optional[Any] = ..., pretask: Optional[Any] = ..., tqdm_class: Any = ..., **tqdm_kwargs: Any) -> None: ...
    def display(self) -> None: ...
