from .std import tqdm as std_tqdm
from typing import Any

class tqdm_gui(std_tqdm):
    mpl: Any = ...
    plt: Any = ...
    toolbar: Any = ...
    mininterval: Any = ...
    xdata: Any = ...
    ydata: Any = ...
    zdata: Any = ...
    hspan: Any = ...
    wasion: Any = ...
    ax: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    disable: bool = ...
    def close(self) -> None: ...
    def clear(self, *_: Any, **__: Any) -> None: ...
    def display(self, *_: Any, **__: Any) -> bool: ...

def tgrange(*args: Any, **kwargs: Any) -> tqdm_gui: ...
tqdm = tqdm_gui
trange = tgrange
