from tensorflow import keras
from typing import Any, Optional

class TqdmCallback(keras.callbacks.Callback):
    @staticmethod
    def bar2callback(bar: Any, pop: Optional[Any] = ..., delta: Any = ...): ...
    tqdm_class: Any = ...
    epoch_bar: Any = ...
    on_epoch_end: Any = ...
    batches: Any = ...
    verbose: Any = ...
    batch_bar: Any = ...
    on_batch_end: Any = ...
    def __init__(self, epochs: Optional[Any] = ..., data_size: Optional[Any] = ..., batch_size: Optional[Any] = ..., verbose: int = ..., tqdm_class: Any = ..., **tqdm_kwargs: Any): ...
    def on_train_begin(self, *_: Any, **__: Any) -> None: ...
    def on_epoch_begin(self, epoch: Any, *_: Any, **__: Any): ...
    def on_train_end(self, *_: Any, **__: Any) -> None: ...
    def display(self) -> None: ...
