from .std import tqdm as std_tqdm
from rich.progress import ProgressColumn
from typing import Any, Optional

class FractionColumn(ProgressColumn):
    unit_scale: Any = ...
    unit_divisor: Any = ...
    def __init__(self, unit_scale: bool = ..., unit_divisor: int = ...) -> None: ...
    def render(self, task: Any): ...

class RateColumn(ProgressColumn):
    unit: Any = ...
    unit_scale: Any = ...
    unit_divisor: Any = ...
    def __init__(self, unit: str = ..., unit_scale: bool = ..., unit_divisor: int = ...) -> None: ...
    def render(self, task: Any): ...

class tqdm_rich(std_tqdm):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def close(self) -> None: ...
    def clear(self, *_: Any, **__: Any) -> None: ...
    def display(self, *_: Any, **__: Any) -> None: ...
    def reset(self, total: Optional[Any] = ...) -> None: ...

def trrange(*args: Any, **kwargs: Any): ...
tqdm = tqdm_rich
trange = trrange
