from .std import tqdm as std_tqdm
from typing import Any, Optional

class tqdm_tk(std_tqdm):
    def __init__(self, *args: Any, **kwargs: Any): ...
    disable: bool = ...
    def close(self) -> None: ...
    def clear(self, *_: Any, **__: Any) -> None: ...
    def display(self, *_: Any, **__: Any) -> None: ...
    def set_description(self, desc: Optional[Any] = ..., refresh: bool = ...) -> None: ...
    desc: Any = ...
    def set_description_str(self, desc: Optional[Any] = ..., refresh: bool = ...) -> None: ...
    def cancel(self) -> None: ...
    def reset(self, total: Optional[Any] = ...) -> None: ...

def ttkrange(*args: Any, **kwargs: Any): ...
tqdm = tqdm_tk
trange = ttkrange
