# Stubs for pandas.tests.tslibs.test_period_asfreq (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


def test_intra_day_conversion_factors(
        freq1: Any, freq2: Any, expected: Any) -> None:
    ...


def test_period_ordinal_start_values(freq: Any, expected: Any) -> None:
    ...


def test_period_ordinal_week(dt: Any, expected: Any) -> None:
    ...


def test_period_ordinal_business_day(day: Any, expected: Any) -> None:
    ...
