# Stubs for pandas.tests.tslibs.test_normalize_date (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from datetime import datetime
from typing import Any


def test_normalize_date(value: Any, expected: Any) -> None:
    ...


class SubDatetime(datetime):
    ...


def test_normalize_date_sub_types(dt: Any, expected: Any) -> None:
    ...
