# Stubs for pandas.tests.tslibs.test_timezones (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


def test_cache_keys_are_distinct_for_pytz_vs_dateutil(tz_name: Any) -> None:
    ...


def test_tzlocal_repr() -> None:
    ...


def test_tzlocal_maybe_get_tz() -> None:
    ...


def test_tzlocal_offset() -> None:
    ...


def infer_setup(request: Any) -> Any:
    ...


def test_infer_tz_compat(infer_setup: Any) -> None:
    ...


def test_infer_tz_utc_localize(infer_setup: Any) -> None:
    ...


def test_infer_tz_mismatch(infer_setup: Any, ordered: Any) -> None:
    ...
