# Stubs for pandas.tests.tslibs.test_array_to_datetime (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from datetime import datetime
from typing import Any


def test_parsing_valid_dates(data: Any, expected: Any) -> None:
    ...


def test_parsing_timezone_offsets(dt_string: Any, expected_tz: Any) -> None:
    ...


def test_parsing_non_iso_timezone_offset() -> None:
    ...


def test_parsing_different_timezone_offsets() -> None:
    ...


def test_number_looking_strings_not_into_datetime(data: Any) -> None:
    ...


def test_coerce_outside_ns_bounds(invalid_date: Any, errors: Any) -> None:
    ...


def test_coerce_outside_ns_bounds_one_valid() -> None:
    ...


def test_coerce_of_invalid_datetimes(errors: Any) -> None:
    ...


def test_to_datetime_barely_out_of_bounds() -> None:
    ...



class SubDatetime(datetime):
    ...



def test_datetime_subclass(data: Any, expected: Any) -> None:
    ...
