# Stubs for pandas.tests.resample.conftest (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

downsample_methods: Any
upsample_methods: Any
series_methods: Any
resample_methods: Any

def downsample_method(request: Any) -> Any:
    ...


def upsample_method(request: Any) -> Any:
    ...


def resample_method(request: Any) -> Any:
    ...


def simple_date_range_series() -> Any:
    ...


def simple_period_range_series() -> Any:
    ...


def index(_index_factory: Any, _index_start: Any, _index_end: Any, _index_freq: Any, _index_name: Any) -> Any:
    ...


def series(index: Any, _series_name: Any, _static_values: Any) -> Any:
    ...


def empty_series(series: Any) -> Any:
    ...


def frame(index: Any, _series_name: Any, _static_values: Any) -> Any:
    ...


def empty_frame(series: Any) -> Any:
    ...


def series_and_frame(request: Any, series: Any, frame: Any) -> Any:
    ...
