# Stubs for pandas.tests.resample.test_time_grouper (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

test_series: Any

def test_apply() -> None:
    ...


def test_count() -> None:
    ...


def test_numpy_reduction() -> None:
    ...


def test_apply_iteration() -> None:
    ...


def test_fails_on_no_datetime_index(name: Any, func: Any) -> None:
    ...


def test_aaa_group_order() -> None:
    ...


def test_aggregate_normal(resample_method: Any) -> None:
    ...


def test_resample_entirly_nat_window(method: Any, method_args: Any, unit: Any) -> None:
    ...


def test_aggregate_with_nat(func: Any, fill_value: Any) -> None:
    ...


def test_aggregate_with_nat_size() -> None:
    ...


def test_repr() -> None:
    ...


def test_upsample_sum(method: Any, method_args: Any, expected_values: Any) -> None:
    ...
