# Stubs for pandas.tests.resample.test_timedelta (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def test_asfreq_bug() -> None:
    ...


def test_resample_with_nat() -> None:
    ...


def test_resample_as_freq_with_subperiod() -> None:
    ...


def test_resample_with_timedeltas() -> None:
    ...


def test_resample_single_period_timedelta() -> None:
    ...


def test_resample_timedelta_idempotency() -> None:
    ...


def test_resample_base_with_timedeltaindex() -> None:
    ...


def test_resample_categorical_data_with_timedeltaindex():
    ...


def test_resample_timedelta_values() -> None:
    ...
