# Stubs for pandas.tests.resample.test_resample_api (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

dti: Any
test_series: Any

def test_frame() -> None:
    ...


def test_str() -> None:
    ...


def test_api() -> None:
    ...


def test_groupby_resample_api() -> None:
    ...


def test_groupby_resample_on_api() -> None:
    ...


def test_pipe(test_frame: Any) -> None:
    ...


def test_getitem(test_frame: Any) -> None:
    ...


def test_select_bad_cols(key: Any, test_frame: Any) -> None:
    ...


def test_attribute_access(test_frame: Any) -> None:
    ...


def test_api_compat_before_use() -> None:
    ...


def tests_skip_nuisance(test_frame: Any) -> None:
    ...


def test_downsample_but_actually_upsampling() -> None:
    ...


def test_combined_up_downsampling_of_irregular() -> None:
    ...


def test_transform() -> None:
    ...


def test_fillna() -> None:
    ...


def test_apply_without_aggregation() -> None:
    ...


def test_agg_consistency() -> None:
    ...


def test_agg() -> None:
    ...


def test_agg_misc() -> None:
    ...


def test_agg_nested_dicts() -> None:
    ...


def test_try_aggregate_non_existing_column() -> None:
    ...


def test_selection_api_validation() -> None:
    ...


def test_agg_with_datetime_index_list_agg_func(col_name: Any) -> None:
    ...
