# Stubs for pandas.tests.resample.test_datetime_index (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

def test_custom_grouper(index: Any) -> None:
    ...


def test_resample_basic(series: Any, closed: Any, expected: Any) -> None:
    ...


def test_resample_integerarray() -> None:
    ...


def test_resample_basic_grouper(series: Any) -> None:
    ...


def test_resample_string_kwargs(series: Any, keyword: Any, value: Any) -> None:
    ...


def test_resample_how(series: Any, downsample_method: Any) -> None:
    ...


def test_resample_how_ohlc(series: Any) -> None:
    ...


def test_numpy_compat(func: Any) -> None:
    ...


def test_resample_how_callables() -> None:
    ...


def test_resample_rounding() -> None:
    ...


def test_resample_basic_from_daily() -> None:
    ...


def test_resample_upsampling_picked_but_not_correct() -> None:
    ...


def test_resample_frame_basic() -> None:
    ...


def test_resample_loffset(loffset: Any) -> None:
    ...


def test_resample_loffset_upsample() -> None:
    ...


def test_resample_loffset_count() -> None:
    ...


def test_resample_upsample() -> None:
    ...


def test_resample_how_method() -> None:
    ...


def test_resample_extra_index_point() -> None:
    ...


def test_upsample_with_limit() -> None:
    ...


def test_nearest_upsample_with_limit() -> None:
    ...


def test_resample_ohlc(series: Any) -> None:
    ...


def test_resample_ohlc_result() -> None:
    ...


def test_resample_ohlc_dataframe() -> None:
    ...


def test_resample_dup_index() -> None:
    ...


def test_resample_reresample() -> None:
    ...


def test_resample_timestamp_to_period(simple_date_range_series: Any) -> None:
    ...


def test_ohlc_5min():
    ...


def test_downsample_non_unique():
    ...


def test_asfreq_non_unique() -> None:
    ...


def test_resample_axis1() -> None:
    ...


def test_resample_anchored_ticks() -> None:
    ...


def test_resample_single_group():
    ...


def test_resample_base() -> None:
    ...


def test_resample_float_base() -> None:
    ...


def test_resample_daily_anchored() -> None:
    ...


def test_resample_to_period_monthly_buglet() -> None:
    ...


def test_period_with_agg():
    ...


def test_resample_segfault():
    ...


def test_resample_dtype_preservation() -> None:
    ...


def test_resample_dtype_coerceion() -> None:
    ...


def test_weekly_resample_buglet() -> None:
    ...


def test_monthly_resample_error() -> None:
    ...


def test_nanosecond_resample_error() -> None:
    ...


def test_resample_anchored_intraday(simple_date_range_series: Any) -> None:
    ...


def test_resample_anchored_monthstart(simple_date_range_series: Any) -> None:
    ...


def test_resample_anchored_multiday() -> None:
    ...


def test_corner_cases(simple_period_range_series: Any, simple_date_range_series: Any) -> None:
    ...


def test_anchored_lowercase_buglet() -> None:
    ...


def test_upsample_apply_functions() -> None:
    ...


def test_resample_not_monotonic() -> None:
    ...


def test_resample_median_bug_1688():
    ...


def test_how_lambda_functions(simple_date_range_series: Any) -> None:
    ...


def test_resample_unequal_times() -> None:
    ...


def test_resample_consistency() -> None:
    ...


def test_resample_timegrouper() -> None:
    ...


def test_resample_nunique():
    ...


def test_resample_nunique_preserves_column_level_names() -> None:
    ...


def test_resample_nunique_with_date_gap() -> None:
    ...


def test_resample_group_info(n: Any, k: Any) -> None:
    ...


def test_resample_size() -> None:
    ...


def test_resample_across_dst() -> None:
    ...


def test_groupby_with_dst_time_change() -> None:
    ...


def test_resample_dst_anchor() -> None:
    ...


def test_downsample_across_dst() -> None:
    ...


def test_downsample_across_dst_weekly() -> None:
    ...


def test_resample_with_nat() -> None:
    ...


def test_resample_datetime_values() -> None:
    ...


def test_resample_apply_with_additional_args(series: Any) -> None:
    ...


def test_resample_equivalent_offsets(n1: Any, freq1: Any, n2: Any, freq2: Any, k: Any) -> None:
    ...


def test_get_timestamp_range_edges(first: Any, last: Any, offset: Any, exp_first: Any, exp_last: Any) -> None:
    ...
