import logging
from ..std import tqdm as std_tqdm
from typing import Any, Iterator, List, Optional, Type

class _TqdmLoggingHandler(logging.StreamHandler):
    tqdm_class: Any = ...
    def __init__(self, tqdm_class: Type[std_tqdm]=...) -> None: ...
    def emit(self, record: Any) -> None: ...

def logging_redirect_tqdm(loggers: Tuple[Optional[List[logging.Logger]]]=..., tqdm_class: Type[std_tqdm]=...) -> Iterator[None]: ...
def tqdm_logging_redirect(*args: Any, **kwargs: Any) -> Iterator[None]: ...
