from ..auto import tqdm as tqdm_auto
from .utils_worker import MonoWorker
from typing import Any

class SlackIO(MonoWorker):
    client: Any = ...
    text: Any = ...
    message: Any = ...
    def __init__(self, token: Any, channel: Any) -> None: ...
    def write(self, s: Any): ...

class tqdm_slack(tqdm_auto):
    sio: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def display(self, **kwargs: Any) -> None: ...
    def clear(self, *args: Any, **kwargs: Any) -> None: ...

def tsrange(*args: Any, **kwargs: Any): ...
tqdm = tqdm_slack
trange = tsrange
