from ..auto import tqdm as tqdm_auto
from .utils_worker import MonoWorker
from typing import Any

class TelegramIO(MonoWorker):
    API: str = ...
    token: Any = ...
    chat_id: Any = ...
    session: Any = ...
    text: Any = ...
    def __init__(self, token: Any, chat_id: Any) -> None: ...
    @property
    def message_id(self): ...
    def write(self, s: Any): ...
    def delete(self): ...

class tqdm_telegram(tqdm_auto):
    tgio: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def display(self, **kwargs: Any) -> None: ...
    def clear(self, *args: Any, **kwargs: Any) -> None: ...
    def close(self) -> None: ...

def ttgrange(*args: Any, **kwargs: Any): ...
tqdm = tqdm_telegram
trange = ttgrange
