# Stubs for pandas.tests.series.indexing.test_iloc (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def test_iloc() -> None:
    ...


def test_iloc_nonunique() -> None:
    ...
