# Stubs for pandas.tests.series.indexing.test_boolean (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any


def test_getitem_boolean(test_data: Any) -> None:
    ...


def test_getitem_boolean_empty() -> None:
    ...


def test_getitem_boolean_object(test_data: Any) -> None:
    ...


def test_getitem_setitem_boolean_corner(test_data: Any) -> None:
    ...


def test_setitem_boolean(test_data: Any) -> None:
    ...


def test_get_set_boolean_different_order(test_data: Any) -> None:
    ...


def test_where_unsafe_int(sint_dtype: Any) -> None:
    ...


def test_where_unsafe_float(float_dtype: Any) -> None:
    ...


def test_where_unsafe_upcast(dtype: Any, expected_dtype: Any) -> None:
    ...


def test_where_unsafe() -> None:
    ...


def test_where() -> None:
    ...


def test_where_error() -> None:
    ...


def test_where_array_like(klass: Any) -> None:
    ...


def test_where_invalid_input(cond: Any) -> None:
    ...


def test_where_ndframe_align() -> None:
    ...


def test_where_setitem_invalid() -> None:
    ...


def test_broadcast(size: Any, mask: Any, item: Any, box: Any) -> None:
    ...


def test_where_inplace() -> None:
    ...


def test_where_dups() -> None:
    ...


def test_where_numeric_with_string() -> None:
    ...


def test_where_timedelta_coerce() -> None:
    ...


def test_where_datetime_conversion() -> None:
    ...


def test_where_dt_tz_values(tz_naive_fixture: Any) -> None:
    ...


def test_mask() -> None:
    ...


def test_mask_inplace() -> None:
    ...
