# Stubs for pandas.tests.series.indexing.test_loc (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

def test_loc_uint64(val: Any, expected: Any) -> None:
    ...


def test_loc_getitem(test_data: Any) -> None:
    ...


def test_loc_getitem_not_monotonic(test_data: Any) -> None:
    ...


def test_loc_getitem_setitem_integer_slice_keyerrors() -> None:
    ...


def test_loc_getitem_iterator(test_data: Any) -> None:
    ...


def test_loc_setitem_boolean(test_data: Any) -> None:
    ...


def test_loc_setitem_corner(test_data: Any) -> None:
    ...


def test_basic_setitem_with_labels(test_data: Any) -> None:
    ...
