# Stubs for pandas.tests.series.indexing.test_numeric (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

def test_get() -> None:
    ...


def test_get_nan() -> None:
    ...


def test_get_nan_multiple() -> None:
    ...


def test_delitem() -> None:
    ...


def test_slice_float64() -> None:
    ...


def test_getitem_negative_out_of_bounds() -> None:
    ...


def test_getitem_regression() -> None:
    ...


def test_getitem_setitem_slice_bug() -> None:
    ...


def test_getitem_setitem_slice_integers() -> None:
    ...


def test_setitem_float_labels() -> None:
    ...


def test_slice_float_get_set(test_data: Any) -> None:
    ...


def test_slice_floats2() -> None:
    ...


def test_int_indexing() -> None:
    ...


def test_getitem_int64(test_data: Any) -> None:
    ...
