# Stubs for pandas.tests.series.indexing.test_callable (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def test_getitem_callable() -> None:
    ...


def test_setitem_callable() -> None:
    ...


def test_setitem_other_callable() -> None:
    ...
