# Stubs for pandas.tests.reshape.test_cut (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

def test_simple() -> None:
    ...


def test_bins() -> None:
    ...


def test_right() -> None:
    ...


def test_no_right() -> None:
    ...


def test_array_like() -> None:
    ...


def test_bins_from_interval_index() -> None:
    ...


def test_bins_from_interval_index_doc_example() -> None:
    ...


def test_bins_not_overlapping_from_interval_index() -> None:
    ...


def test_bins_not_monotonic() -> None:
    ...


def test_bins_monotonic_not_overflowing(x: Any, bins: Any, expected: Any) -> None:
    ...


def test_wrong_num_labels() -> None:
    ...


def test_cut_corner(x: Any, bins: Any, msg: Any) -> None:
    ...


def test_cut_not_1d_arg(arg: Any, cut_func: Any) -> None:
    ...


def test_int_bins_with_inf(data: Any) -> None:
    ...


def test_cut_out_of_range_more() -> None:
    ...


def test_labels(right: Any, breaks: Any, closed: Any) -> None:
    ...


def test_cut_pass_series_name_to_factor() -> None:
    ...


def test_label_precision() -> None:
    ...


def test_na_handling(labels: Any) -> None:
    ...


def test_inf_handling() -> None:
    ...


def test_cut_out_of_bounds() -> None:
    ...


def test_cut_pass_labels(get_labels: Any, get_expected: Any) -> None:
    ...


def test_cut_pass_labels_compat() -> None:
    ...


def test_round_frac_just_works(x: Any) -> None:
    ...


def test_round_frac(val: Any, precision: Any, expected: Any) -> None:
    ...


def test_cut_return_intervals() -> None:
    ...


def test_series_ret_bins() -> None:
    ...


def test_cut_duplicates_bin(kwargs: Any, msg: Any) -> None:
    ...


def test_single_bin(data: Any, length: Any) -> None:
    ...


def test_cut_read_only(array_1_writeable: Any, array_2_writeable: Any) -> None:
    ...


def test_datetime_bin(conv: Any) -> None:
    ...


def test_datetime_cut(data: Any) -> None:
    ...


def test_datetime_tz_cut(bins: Any, box: Any) -> None:
    ...


def test_datetime_nan_error() -> None:
    ...


def test_datetime_nan_mask() -> None:
    ...


def test_datetime_cut_roundtrip(tz: Any) -> None:
    ...


def test_timedelta_cut_roundtrip() -> None:
    ...
