# Stubs for pandas.tests.sparse.series.test_indexing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any

pytestmark: Any


def test_where_with_numeric_data(data: Any) -> None:
    ...


def test_where_with_numeric_data_and_other(data: Any, other: Any) -> None:
    ...


def test_where_with_bool_data() -> None:
    ...


def test_where_with_bool_data_and_other(other: Any) -> None:
    ...
