# Stubs for pandas.tests.indexes.period.test_ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ

from typing import Any
from pandas.tests.test_base import Ops

class TestPeriodIndexOps(Ops):
    is_valid_objs: Any = ...
    not_valid_objs: Any = ...
    def setup_method(self, method: Any) -> Any:
        ...

    def test_ops_properties(self):
        ...

    def test_resolution(self) -> None:
        ...

    def test_value_counts_unique(self) -> None:
        ...

    def test_drop_duplicates_metadata(self) -> None:
        ...

    def test_drop_duplicates(self) -> None:
        ...

    def test_order_compat(self) -> None:
        ...

    def test_order(self) -> None:
        ...

    def test_shift(self) -> None:
        ...

    def test_nat(self) -> None:
        ...

    def test_equals(self, freq: Any) -> None:
        ...

    def test_freq_setter_deprecated(self) -> None:
        ...
