# Stubs for pandas.tests.indexes.period.test_scalar_compat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ

class TestPeriodIndexOps:
    def test_start_time(self) -> None:
        ...

    def test_end_time(self) -> None:
        ...
