# Stubs for pandas.tests.indexes.period.test_period_range (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ

from typing import Any


class TestPeriodRange:
    def test_construction_from_string(self, freq: Any) -> None:
        ...

    def test_construction_from_period(self) -> None:
        ...

    def test_errors(self) -> None:
        ...
