# Stubs for pandas.tests.frame.common (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any

class TestData:
    def frame(self) -> Any:
        ...

    def frame2(self) -> Any:
        ...

    def intframe(self) -> Any:
        ...

    def tsframe(self) -> Any:
        ...

    def mixed_frame(self) -> Any:
        ...

    def mixed_float(self) -> Any:
        ...

    def mixed_float2(self) -> Any:
        ...

    def mixed_int(self) -> Any:
        ...

    def all_mixed(self) -> Any:
        ...

    def tzframe(self) -> Any:
        ...

    def empty(self) -> Any:
        ...

    def ts1(self) -> Any:
        ...

    def ts2(self) -> Any:
        ...

    def simple(self) -> Any:
        ...
