# Stubs for pandas.tests.frame.conftest (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any


def float_frame_with_na() -> Any:
    ...


def bool_frame_with_na() -> Any:
    ...


def int_frame() -> Any:
    ...


def datetime_frame() -> Any:
    ...


def float_string_frame() -> Any:
    ...


def mixed_float_frame() -> Any:
    ...


def mixed_int_frame() -> Any:
    ...


def mixed_type_frame() -> Any:
    ...


def timezone_frame() -> Any:
    ...


def uint64_frame() -> Any:
    ...


def simple_frame() -> Any:
    ...


def frame_of_index_cols() -> Any:
    ...
