# Stubs for pandas.tests.frame.test_rank (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


class TestRank:
    s: Any = ...
    df: Any = ...
    results: Any = ...

    def method(self, request: Any) -> Any:
        ...

    def test_rank(self, float_frame: Any) -> None:
        ...

    def test_rank2(self) -> None:
        ...

    def test_rank_mixed_frame(self, float_string_frame: Any) -> None:
        ...

    def test_rank_na_option(self, float_frame: Any) -> None:
        ...

    def test_rank_axis(self) -> None:
        ...

    def test_rank_methods_frame(self) -> None:
        ...

    def test_rank_descending(self, method: Any, dtype: Any) -> None:
        ...

    def test_rank_2d_tie_methods(
            self, method: Any, axis: Any, dtype: Any) -> None:
        ...

    def test_rank_pct_true(self, method: Any, exp: Any) -> None:
        ...

    def test_pct_max_many_rows(self) -> None:
        ...
