# Stubs for pandas.tests.frame.test_sorting (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any
from pandas.tests.frame.common import TestData


class TestDataFrameSorting(TestData):
    def test_sort_values(self) -> None:
        ...

    def test_sort_values_inplace(self) -> None:
        ...

    def test_sort_nan(self) -> None:
        ...

    def test_stable_descending_sort(self) -> None:
        ...

    def test_stable_descending_multicolumn_sort(self) -> None:
        ...

    def test_sort_multi_index(self) -> None:
        ...

    def test_stable_categorial(self) -> None:
        ...

    def test_sort_datetimes(self) -> None:
        ...

    def test_frame_column_inplace_sort_exception(self) -> None:
        ...

    def test_sort_nat_values_in_int_column(self) -> None:
        ...

    def test_sort_nat(self) -> None:
        ...


class TestDataFrameSortIndexKinds(TestData):
    def test_sort_index_multicolumn(self) -> None:
        ...

    def test_sort_index_inplace(self) -> None:
        ...

    def test_sort_index_different_sortorder(self) -> None:
        ...

    def test_sort_index_duplicates(self) -> None:
        ...

    def test_sort_index_level(self) -> None:
        ...

    def test_sort_index_categorical_index(self) -> None:
        ...

    def test_sort_index(self) -> None:
        ...

    def test_sort_index_multiindex(self, level: Any) -> None:
        ...

    def test_sort_index_intervalindex(self) -> None:
        ...

    def test_sort_index_na_position_with_categories(self) -> None:
        ...

    def test_sort_index_na_position_with_categories_raises(self) -> None:
        ...
