# Stubs for pandas.tests.frame.test_duplicates (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


def test_duplicated_with_misspelled_column_name(subset: Any) -> None:
    ...


def test_duplicated_do_not_fail_on_wide_dataframes() -> None:
    ...


def test_duplicated_keep(keep: Any, expected: Any) -> None:
    ...


def test_duplicated_nan_none(keep: Any, expected: Any) -> None:
    ...


def test_duplicated_subset(subset: Any, keep: Any) -> None:
    ...


def test_drop_duplicates() -> None:
    ...


def test_duplicated_on_empty_frame() -> None:
    ...


def test_drop_duplicates_with_duplicate_column_names() -> None:
    ...


def test_drop_duplicates_for_take_all() -> None:
    ...


def test_drop_duplicates_tuple() -> None:
    ...


def test_drop_duplicates_empty(df: Any) -> None:
    ...


def test_drop_duplicates_NA() -> None:
    ...


def test_drop_duplicates_NA_for_take_all() -> None:
    ...


def test_drop_duplicates_inplace() -> None:
    ...
