# Stubs for pandas.tests.frame.test_alter_axes (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


class TestDataFrameAlterAxes:
    def test_set_index_directly(self, float_string_frame: Any) -> None:
        ...

    def test_set_index(self, float_string_frame: Any) -> None:
        ...

    def test_set_index_cast(self) -> None:
        ...

    def test_set_index_drop_inplace(
            self, frame_of_index_cols: Any, drop: Any, inplace: Any,
            keys: Any) -> None:
        ...

    def test_set_index_append(
            self, frame_of_index_cols: Any, drop: Any, keys: Any) -> None:
        ...

    def test_set_index_append_to_multiindex(
            self, frame_of_index_cols: Any, drop: Any, keys: Any) -> None:
        ...

    def test_set_index_after_mutation(self):
        ...

    def test_set_index_pass_single_array(
            self, frame_of_index_cols: Any, drop: Any, append: Any,
            index_name: Any, box: Any) -> None:
        ...

    def test_set_index_pass_arrays(
            self, frame_of_index_cols: Any, drop: Any, append: Any,
            index_name: Any, box: Any) -> None:
        ...

    def test_set_index_pass_arrays_duplicate(
            self, frame_of_index_cols: Any, drop: Any, append: Any,
            index_name: Any, box1: Any, box2: Any) -> None:
        ...

    def test_set_index_pass_multiindex(
            self, frame_of_index_cols: Any, drop: Any, append: Any) -> None:
        ...

    def test_set_index_verify_integrity(
            self, frame_of_index_cols: Any) -> None:
        ...

    def test_set_index_raise_keys(
            self, frame_of_index_cols: Any, drop: Any, append: Any) -> None:
        ...

    def test_set_index_raise_on_type(
            self, frame_of_index_cols: Any, box: Any, drop: Any,
            append: Any) -> None:
        ...

    def test_set_index_raise_on_len(
            self, frame_of_index_cols: Any, box: Any, length: Any, drop: Any,
            append: Any) -> None:
        ...

    name: Any = ...
    color: Any = ...

    def test_set_index_custom_label_type(self) -> None:
        ...

    def test_set_index_custom_label_hashable_iterable(self) -> None:
        ...

    def test_set_index_custom_label_type_raises(self):
        ...

    def test_construction_with_categorical_index(self) -> None:
        ...

    def test_set_index_cast_datetimeindex(self) -> None:
        ...

    def test_convert_dti_to_series(self) -> None:
        ...

    def test_reset_index_tz(self, tz_aware_fixture: Any) -> None:
        ...

    def test_set_index_timezone(self) -> None:
        ...

    def test_set_index_dst(self) -> None:
        ...

    def test_reset_index_with_intervals(self) -> None:
        ...

    def test_set_index_multiindexcolumns(self) -> None:
        ...

    def test_set_index_empty_column(self) -> None:
        ...

    def test_set_columns(self, float_string_frame: Any) -> None:
        ...

    def test_dti_set_index_reindex(self) -> None:
        ...

    def test_rename(self, float_frame: Any) -> None:
        ...

    def test_rename_axis_inplace(self, float_frame: Any) -> None:
        ...

    def test_rename_axis_raises(self) -> None:
        ...

    def test_rename_axis_mapper(self) -> None:
        ...

    def test_rename_axis_none(
            self, kwargs: Any, rename_index: Any, rename_columns: Any) -> None:
        ...

    def test_rename_multiindex(self) -> None:
        ...

    def test_rename_nocopy(self, float_frame: Any) -> None:
        ...

    def test_rename_inplace(self, float_frame: Any) -> None:
        ...

    def test_rename_bug(self) -> None:
        ...

    def test_rename_bug2(self) -> None:
        ...

    def test_rename_errors_raises(self) -> None:
        ...

    def test_rename_errors(
            self, mapper: Any, errors: Any, expected_columns: Any) -> None:
        ...

    def test_reorder_levels(self) -> None:
        ...

    def test_reset_index(self, float_frame: Any) -> None:
        ...

    def test_reset_index_name(self) -> None:
        ...

    def test_reset_index_level(self) -> None:
        ...

    def test_reset_index_right_dtype(self) -> None:
        ...

    def test_reset_index_multiindex_col(self) -> None:
        ...

    def test_reset_index_multiindex_nan(self) -> None:
        ...

    def test_reset_index_with_datetimeindex_cols(self) -> None:
        ...

    def test_reset_index_range(self) -> None:
        ...

    def test_set_index_names(self) -> None:
        ...

    def test_rename_objects(self, float_string_frame: Any) -> None:
        ...

    def test_rename_axis_style(self) -> None:
        ...

    def test_rename_mapper_multi(self) -> None:
        ...

    def test_rename_positional_named(self) -> None:
        ...

    def test_rename_axis_style_raises(self) -> None:
        ...

    def test_reindex_api_equivalence(self) -> None:
        ...

    def test_rename_positional(self) -> None:
        ...

    def test_assign_columns(self, float_frame: Any) -> None:
        ...

    def test_set_index_preserve_categorical_dtype(self) -> None:
        ...

    def test_ambiguous_warns(self) -> None:
        ...

    def test_rename_signature(self) -> None:
        ...

    def test_reindex_signature(self) -> None:
        ...

    def test_droplevel(self) -> None:
        ...


class TestIntervalIndex:
    def test_setitem(self):
        ...

    def test_set_reset_index(self) -> None:
        ...

    def test_set_axis_inplace(self) -> None:
        ...

    def test_set_axis_prior_to_deprecation_signature(self) -> None:
        ...
