# Stubs for pandas.tests.config.test_localization (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any

pytestmark: Any


def test_can_set_locale_valid_set() -> None:
    ...


def test_can_set_locale_invalid_set() -> None:
    ...


def test_can_set_locale_invalid_get(monkeypatch: Any) -> None:
    ...


def test_get_locales_at_least_one() -> None:
    ...


def test_get_locales_prefix() -> None:
    ...


def test_set_locale() -> None:
    ...
