# Stubs for pandas.tests.window.test_ewm (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any
from pandas.tests.window.common import Base


class TestEWM(Base):
    def setup_method(self, method: Any) -> None:
        ...

    def test_doc_string(self) -> None:
        ...

    def test_constructor(self, which: Any) -> None:
        ...

    def test_numpy_compat(self, method: Any) -> None:
        ...
