# Stubs for pandas.tests.window.test_expanding (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any
from pandas.tests.window.common import Base

class TestExpanding(Base):
    def setup_method(self, method: Any) -> None:
        ...

    def test_doc_string(self) -> None:
        ...

    def test_constructor(self, which: Any) -> None:
        ...

    def test_numpy_compat(self, method: Any) -> None:
        ...

    def test_empty_df_expanding(self, expander: Any) -> None:
        ...

    def test_missing_minp_zero(self) -> None:
        ...

    def test_iter_raises(self, klass: Any) -> None:
        ...

    def test_expanding_axis(self, axis_frame: Any) -> None:
        ...
