# Stubs for pandas._libs.tslibs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument

from typing import Any


class IntervalMixin:
    @property
    def closed_left(self) -> Any:
        ...

    @property
    def closed_right(self) -> Any:
        ...

    @property
    def open_left(self) -> Any:
        ...

    @property
    def open_right(self) -> Any:
        ...

    @property
    def mid(self) -> Any:
        ...

    @property
    def length(self) -> Any:
        ...

    @property
    def is_empty(self) -> bool:
        ...

    def _check_closed_matches(self, other: Any, name: str = 'other') -> Any:
        ...


class Interval(IntervalMixin):
    def __init__(self, left: Any, right: Any, closed: str = 'right') -> None:
        ...

    def _validate_endpoint(self, endpoint: Any) -> None:
        ...

    def __hash__(self) -> int:
        ...

    def __contains__(self, key: Any) -> bool:
        ...

    def __richcmp__(self, other: Any, op: int) -> Any:
        ...

    def __reduce__(self) -> Any:
        ...

    def _repr_base(self) -> Any:
        ...

    def __repr__(self) -> str:
        ...

    def __str__(self) -> str:
        ...

    def __add__(self, y: Any) -> Any:
        ...

    def __sub__(self, y: Any) -> Any:
        ...

    def __mul__(self, y: Any) -> Any:
        ...

    def __div__(self, y: Any) -> Any:
        ...

    def __truediv__(self, y: Any) -> Any:
        ...

    def __floordiv__(self, y: Any) -> Any:
        ...

    def overlaps(self, other: Any) -> Any:
        ...
