# Stubs for pandas.tests.io.msgpack.test_subtype (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from collections import namedtuple

class MyList(list):
    ...


class MyDict(dict):
    ...


class MyTuple(tuple):
    ...



MyNamedTuple = namedtuple('MyNamedTuple', 'x y')

def test_types() -> None:
    ...
