# Stubs for pandas.tests.io.msgpack.test_newspec (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin


def test_str8() -> None:
    ...


def test_bin8() -> None:
    ...


def test_bin16() -> None:
    ...


def test_bin32() -> None:
    ...


def test_ext() -> None:
    ...
