# Stubs for pandas.tests.io.msgpack.test_except (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

class DummyException(Exception):
    ...


class TestExceptions:
    def test_raise_on_find_unsupported_value(self) -> None:
        ...

    def test_raise_from_object_hook(self) -> None:
        ...

    def test_invalid_value(self) -> None:
        ...
