# Stubs for pandas.tests.io.msgpack.test_read_size (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

UnexpectedTypeException = ValueError

def test_read_array_header() -> None:
    ...


def test_read_map_header() -> None:
    ...


def test_incorrect_type_array() -> None:
    ...


def test_incorrect_type_map() -> None:
    ...


def test_correct_type_nested_array() -> None:
    ...


def test_incorrect_type_nested_map() -> None:
    ...
