name: Python Checks

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Cache python modules ${{ matrix.python }}
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements.lint.txt') }}

    - name: Install dependencies
      run: |
        make install

    - name: Local installation of package
      run: |
        pip install -e .

    - name: Git Check (tests may not alter any git visible files)
      run: |
        git status -sb --porcelain
        [ -z "$(git status --porcelain)" ]

    - name: Lint Code (use uppercase TODO, XXX, FIXME, NOTE and explain nopep8)
      if: ${{ matrix.python == '3.9'}}
      run: |
        make lint-comment

    - name: Lint Code (use empty main inits)
      if: ${{ matrix.python == '3.9'}}
      run: |
        make lint-emptyinit

    - name: Lint Code (sort requirements)
      if: ${{ matrix.python == '3.9'}}
      run: |
        make lint-requirements

    - name: Lint Code (use f"" style formating)
      if: ${{ matrix.python == '3.9'}}
      run: |
        make lint-stringformat

    - name: Lint Code (indent in fours)
      if: ${{ matrix.python == '3.9'}}
      run: |
        make lint-indent

    - name: Lint Code (no f"a", "{a}", or f'{a}')
      if: ${{ matrix.python == '3.9'}}
      run: |
        make lint-forgottenformat

    - name: Only pyi in stubs
      if: ${{ matrix.python == '3.9'}}
      run: |
        make lint-pyi

    - name: Lint Code (missing trailing comma)
      if: ${{ matrix.python == '3.9'}}
      run: |
        make lint-flake8

    - name: Lint Code (pycodestyle)
      if: ${{ matrix.python == '3.9'}}
      run: |
        make lint-pycodestyle

    - name: Lint Code (type-check)
      run: |
        make lint-type-check

    - name: Lint Code (pylint)
      run: |
        make lint-pylint

    - name: Run Tests Coverage
      run: |
        make coverage-report

    - name: SonarQube
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
