# Stubs for pandas.tests.tseries.holiday.test_holiday (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any

def test_holiday_dates(
        holiday: Any, start_date: Any, end_date: Any, expected: Any) -> None:
    ...


def test_holidays_within_dates(
        holiday: Any, start: Any, expected: Any) -> None:
    ...


def test_argument_types(transform: Any) -> None:
    ...


def test_special_holidays(name: Any, kwargs: Any) -> None:
    ...


def test_get_calendar() -> None:
    ...


def test_factory() -> None:
    ...


def test_both_offset_observance_raises() -> None:
    ...
