# Stubs for pandas.tests.indexes.interval.test_interval_new (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long

from typing import Any


class TestIntervalIndex:
    def test_get_loc_interval(self, closed: Any, side: Any) -> None:
        ...

    def test_get_loc_scalar(self, closed: Any, scalar: Any) -> None:
        ...

    def test_slice_locs_with_interval(self) -> None:
        ...

    def test_slice_locs_with_ints_and_floats_succeeds(self) -> None:
        ...

    def test_slice_locs_with_ints_and_floats_errors(self, tuples: Any, query: Any) -> None:
        ...

    def test_get_indexer_with_interval(self, query: Any, expected: Any) -> None:
        ...

    def test_get_indexer_with_int_and_float(self, query: Any, expected: Any) -> None:
        ...

    def test_get_indexer_errors(self, tuples: Any, closed: Any) -> None:
        ...

    def test_get_indexer_non_unique_with_int_and_float(self, query: Any, expected: Any) -> None:
        ...

    def test_contains_dunder(self) -> None:
        ...
