# Stubs for pandas.tests.sparse.test_combine_concat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


class TestSparseArrayConcat:
    def test_basic(self, kind: Any) -> None:
        ...

    def test_uses_first_kind(self, kind: Any) -> None:
        ...


class TestSparseSeriesConcat:
    def test_concat(self, kind: Any) -> None:
        ...

    def test_concat_axis1(self) -> None:
        ...

    def test_concat_different_fill(self) -> None:
        ...

    def test_concat_axis1_different_fill(self) -> None:
        ...

    def test_concat_different_kind(self) -> None:
        ...

    def test_concat_sparse_dense(self, kind: Any) -> None:
        ...


class TestSparseDataFrameConcat:
    dense1: Any = ...
    dense2: Any = ...
    dense3: Any = ...

    def setup_method(self, method: Any) -> None:
        ...

    def test_concat(self) -> None:
        ...

    def test_concat_different_fill_value(self) -> None:
        ...

    def test_concat_different_columns_sort_warns(self) -> None:
        ...

    def test_concat_different_columns(self) -> None:
        ...

    def test_concat_bug(self) -> None:
        ...

    def test_concat_different_columns_buggy(self) -> None:
        ...

    def test_concat_series(self) -> None:
        ...

    def test_concat_axis1(self) -> None:
        ...

    def test_concat_sparse_dense_rows(
            self, fill_value: Any, sparse_idx: Any, dense_idx: Any) -> None:
        ...

    def test_concat_sparse_dense_cols(
            self, fill_value: Any, sparse_idx: Any, dense_idx: Any) -> None:
        ...
