# Stubs for pandas.tests.sparse.test_groupby (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


class TestSparseGroupBy:
    dense: Any = ...
    sparse: Any = ...

    def setup_method(self, method: Any) -> None:
        ...

    def test_first_last_nth(self) -> None:
        ...

    def test_aggfuncs(self) -> None:
        ...


def test_groupby_includes_fill_value(fill_value: Any) -> None:
    ...
