# Stubs for pandas.tests.sparse.test_reshape (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level

from typing import Any


def sparse_df():
    ...


def multi_index3():
    ...


def test_sparse_frame_stack(sparse_df: Any, multi_index3: Any) -> None:
    ...


def test_sparse_frame_unstack(sparse_df: Any) -> None:
    ...


def test_sparse_series_unstack(sparse_df: Any, multi_index3: Any) -> None:
    ...
