# Stubs for pandas.tests.io.parser.test_dtypes (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

def test_dtype_all_columns(all_parsers: Any, dtype: Any, check_orig: Any) -> None:
    ...


def test_dtype_all_columns_empty(all_parsers: Any) -> None:
    ...


def test_dtype_per_column(all_parsers: Any) -> None:
    ...


def test_invalid_dtype_per_column(all_parsers: Any) -> None:
    ...


def test_categorical_dtype(all_parsers: Any, dtype: Any) -> None:
    ...


def test_categorical_dtype_single(all_parsers: Any, dtype: Any) -> None:
    ...


def test_categorical_dtype_unsorted(all_parsers: Any) -> None:
    ...


def test_categorical_dtype_missing(all_parsers: Any) -> None:
    ...


def test_categorical_dtype_high_cardinality_numeric(all_parsers: Any) -> None:
    ...


def test_categorical_dtype_latin1(all_parsers: Any, csv_dir_path: Any) -> None:
    ...


def test_categorical_dtype_utf16(all_parsers: Any, csv_dir_path: Any) -> None:
    ...


def test_categorical_dtype_chunksize_infer_categories(all_parsers: Any) -> None:
    ...


def test_categorical_dtype_chunksize_explicit_categories(all_parsers: Any) -> None:
    ...


def test_categorical_category_dtype(all_parsers: Any, categories: Any, ordered: Any) -> None:
    ...


def test_categorical_category_dtype_unsorted(all_parsers: Any) -> None:
    ...


def test_categorical_coerces_numeric(all_parsers: Any) -> None:
    ...


def test_categorical_coerces_datetime(all_parsers: Any) -> None:
    ...


def test_categorical_coerces_timestamp(all_parsers: Any) -> None:
    ...


def test_categorical_coerces_timedelta(all_parsers: Any) -> None:
    ...


def test_categorical_dtype_coerces_boolean(all_parsers: Any, data: Any) -> None:
    ...


def test_categorical_unexpected_categories(all_parsers: Any) -> None:
    ...


def test_empty_pass_dtype(all_parsers: Any) -> None:
    ...


def test_empty_with_index_pass_dtype(all_parsers: Any) -> None:
    ...


def test_empty_with_multi_index_pass_dtype(all_parsers: Any) -> None:
    ...


def test_empty_with_mangled_column_pass_dtype_by_names(all_parsers: Any) -> None:
    ...


def test_empty_with_mangled_column_pass_dtype_by_indexes(all_parsers: Any) -> None:
    ...


def test_empty_with_dup_column_pass_dtype_by_indexes(all_parsers: Any) -> None:
    ...


def test_empty_with_dup_column_pass_dtype_by_indexes_raises(all_parsers: Any) -> None:
    ...


def test_raise_on_passed_int_dtype_with_nas(all_parsers: Any) -> None:
    ...


def test_dtype_with_converters(all_parsers: Any) -> None:
    ...


def test_empty_dtype(all_parsers: Any, dtype: Any, expected: Any) -> None:
    ...


def test_numeric_dtype(all_parsers: Any, dtype: Any) -> None:
    ...
