# Stubs for pandas.tests.io.parser.test_python_parser_only (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

def test_default_separator(python_parser_only: Any) -> None:
    ...


def test_invalid_skipfooter_non_int(python_parser_only: Any, skipfooter: Any) -> None:
    ...


def test_invalid_skipfooter_negative(python_parser_only: Any) -> None:
    ...


def test_sniff_delimiter(python_parser_only: Any, kwargs: Any) -> None:
    ...


def test_sniff_delimiter_encoding(python_parser_only: Any, encoding: Any) -> None:
    ...


def test_single_line(python_parser_only: Any) -> None:
    ...


def test_skipfooter(python_parser_only: Any, kwargs: Any) -> None:
    ...


def test_decompression_regex_sep(python_parser_only: Any, csv1: Any, compression: Any, klass: Any) -> None:
    ...


def test_read_csv_buglet_4x_multi_index(python_parser_only: Any) -> None:
    ...


def test_read_csv_buglet_4x_multi_index2(python_parser_only: Any) -> None:
    ...


def test_skipfooter_with_decimal(python_parser_only: Any, add_footer: Any) -> None:
    ...


def test_encoding_non_utf8_multichar_sep(python_parser_only: Any, sep: Any, encoding: Any) -> None:
    ...


def test_multi_char_sep_quotes(python_parser_only: Any, quoting: Any) -> None:
    ...


def test_none_delimiter(python_parser_only: Any, capsys: Any) -> None:
    ...


def test_skipfooter_bad_row(python_parser_only: Any, data: Any, skipfooter: Any) -> None:
    ...


def test_malformed_skipfooter(python_parser_only: Any) -> None:
    ...
