# Stubs for pandas.tests.io.parser.test_quoting (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Any

def test_bad_quote_char(all_parsers: Any, kwargs: Any, msg: Any) -> None:
    ...


def test_bad_quoting(all_parsers: Any, quoting: Any, msg: Any) -> None:
    ...


def test_quote_char_basic(all_parsers: Any) -> None:
    ...


def test_quote_char_various(all_parsers: Any, quote_char: Any) -> None:
    ...


def test_null_quote_char(all_parsers: Any, quoting: Any, quote_char: Any) -> None:
    ...


def test_quoting_various(all_parsers: Any, kwargs: Any, exp_data: Any) -> None:
    ...


def test_double_quote(all_parsers: Any, doublequote: Any, exp_data: Any) -> None:
    ...


def test_quotechar_unicode(all_parsers: Any, quotechar: Any) -> None:
    ...


def test_unbalanced_quoting(all_parsers: Any, balanced: Any) -> None:
    ...
